import type { LucideIcon } from "lucide-react";
import { Building2, GraduationCap, Handshake, ShoppingBag, Truck, Warehouse } from "lucide-react";

export type Locale = "fr" | "en" | "ro" | "pt" | "ar";
export const localeMeta: Record<Locale, { label: string; short: string; dir: "ltr" | "rtl" }> = {
  fr: { label: "Français", short: "FR", dir: "ltr" }, en: { label: "English", short: "EN", dir: "ltr" }, ro: { label: "Română", short: "RO", dir: "ltr" }, pt: { label: "Português", short: "PT", dir: "ltr" }, ar: { label: "العربية", short: "AR", dir: "rtl" },
};

const navigationTranslations = {
  fr: { home: "Accueil", start: "Démarrer mon projet", study: "Étudier à l’étranger", universities: "Universités", services: "Nos services", partners: "Partenaires", workPermits: "Permis de travail", dossier: "Mon dossier ICX", login: "Se connecter", directory: "Répertoire institutionnel", officialSource: "Source officielle", searchPlaceholder: "Rechercher un établissement, un pays ou une ville", filter: "Filtrer", officialSite: "Site officiel", admission: "Admission", viewFile: "Voir la fiche", team: "Notre équipe", workTitle: "Permis de travail en Europe", workIntro: "ICX propose une orientation et une assistance administrative pour les personnes qui souhaitent travailler en Roumanie ou en Pologne.", workCaution: "Les autorisations dépendent du profil, de l’employeur et des autorités compétentes. ICX ne garantit ni l’obtention d’un emploi ni la délivrance d’un permis.", countries: "Pays couverts", association: "Association", aaftNote: "AAFT est une association créée en Roumanie par Jean Lansana KOUNDOUNO et K Marcel TRAORE. Elle n’est pas une université.", support: "Orientation, admission et assistance administrative", supportText: "ICX peut conseiller les candidats dans la recherche d’un programme, la préparation d’une demande d’admission, l’accueil et les démarches administratives liées au séjour étudiant, toujours selon les règles et sources officielles du pays concerné." },
  en: { home: "Home", start: "Start my project", study: "Study abroad", universities: "Universities", services: "Services", partners: "Partners", workPermits: "Work permits", dossier: "My ICX file", login: "Sign in", directory: "Institution directory", officialSource: "Official source", searchPlaceholder: "Search an institution, country or city", filter: "Filter", officialSite: "Official website", admission: "Admissions", viewFile: "View profile", team: "Our team", workTitle: "Work permits in Europe", workIntro: "ICX provides guidance and administrative assistance for people who wish to work in Romania or Poland.", workCaution: "Authorisations depend on the applicant, employer and competent authorities. ICX does not guarantee employment or permit approval.", countries: "Countries covered", association: "Association", aaftNote: "AAFT is an association created in Romania by Jean Lansana KOUNDOUNO and K Marcel TRAORE. It is not a university.", support: "Guidance, admissions and administrative assistance", supportText: "ICX may advise candidates on programme research, admission applications, reception and administrative steps related to student residence, always according to the official rules and sources of the country concerned." },
  ro: { home: "Acasă", start: "Începe proiectul", study: "Studii în străinătate", universities: "Universități", services: "Servicii", partners: "Parteneri", workPermits: "Permise de muncă", dossier: "Dosarul meu ICX", login: "Autentificare", directory: "Director instituțional", officialSource: "Sursă oficială", searchPlaceholder: "Caută o instituție, o țară sau un oraș", filter: "Filtrează", officialSite: "Site oficial", admission: "Admitere", viewFile: "Vezi profilul", team: "Echipa noastră", workTitle: "Permise de muncă în Europa", workIntro: "ICX oferă orientare și asistență administrativă persoanelor care doresc să lucreze în România sau Polonia.", workCaution: "Autorizațiile depind de profil, angajator și autoritățile competente. ICX nu garantează un loc de muncă sau aprobarea permisului.", countries: "Țări acoperite", association: "Asociație", aaftNote: "AAFT este o asociație creată în România de Jean Lansana KOUNDOUNO și K Marcel TRAORE. Nu este o universitate.", support: "Orientare, admitere și asistență administrativă", supportText: "ICX poate consilia candidații în căutarea unui program, pregătirea cererii de admitere, primire și proceduri administrative pentru șederea studențească, conform surselor oficiale." },
  pt: { home: "Início", start: "Iniciar projeto", study: "Estudar no exterior", universities: "Universidades", services: "Serviços", partners: "Parceiros", workPermits: "Permissões de trabalho", dossier: "Meu dossiê ICX", login: "Entrar", directory: "Diretório institucional", officialSource: "Fonte oficial", searchPlaceholder: "Pesquisar instituição, país ou cidade", filter: "Filtrar", officialSite: "Site oficial", admission: "Admissão", viewFile: "Ver perfil", team: "Nossa equipa", workTitle: "Permissões de trabalho na Europa", workIntro: "A ICX oferece orientação e assistência administrativa para pessoas que desejam trabalhar na Roménia ou na Polónia.", workCaution: "As autorizações dependem do perfil, empregador e autoridades competentes. A ICX não garante emprego nem aprovação da permissão.", countries: "Países cobertos", association: "Associação", aaftNote: "A AAFT é uma associação criada na Roménia por Jean Lansana KOUNDOUNO e K Marcel TRAORE. Não é uma universidade.", support: "Orientação, admissão e assistência administrativa", supportText: "A ICX pode orientar candidatos na pesquisa de programas, pedidos de admissão, acolhimento e procedimentos administrativos de residência estudantil, segundo fontes oficiais." },
  ar: { home: "الرئيسية", start: "ابدأ مشروعك", study: "الدراسة بالخارج", universities: "الجامعات", services: "الخدمات", partners: "الشركاء", workPermits: "تصاريح العمل", dossier: "ملفي لدى ICX", login: "تسجيل الدخول", directory: "دليل المؤسسات", officialSource: "مصدر رسمي", searchPlaceholder: "ابحث عن مؤسسة أو بلد أو مدينة", filter: "تصفية", officialSite: "الموقع الرسمي", admission: "القبول", viewFile: "عرض الملف", team: "فريقنا", workTitle: "تصاريح العمل في أوروبا", workIntro: "تقدم ICX التوجيه والمساعدة الإدارية للأشخاص الراغبين في العمل في رومانيا أو بولندا.", workCaution: "تعتمد التصاريح على الملف وصاحب العمل والسلطات المختصة. لا تضمن ICX الحصول على وظيفة أو الموافقة على التصريح.", countries: "البلدان المشمولة", association: "جمعية", aaftNote: "AAFT جمعية أنشأها في رومانيا Jean Lansana KOUNDOUNO وK Marcel TRAORE. وهي ليست جامعة.", support: "التوجيه والقبول والمساعدة الإدارية", supportText: "يمكن لـ ICX تقديم المشورة بشأن البرامج وطلبات القبول والاستقبال والإجراءات الإدارية للإقامة الطلابية، وفق المصادر الرسمية." },
} as const;

const pageTranslations = {
  fr: {
    layout: {
      homeAria: "Accueil ICX POWER SOLUTIONS",
      navAria: "Navigation principale",
      theme: "Changer le thème",
      language: "Choisir la langue",
      openMenu: "Ouvrir le menu",
      closeMenu: "Fermer le menu",
      backToTop: "Revenir en haut de la page",
      projectStudy: "Études",
      projectWork: "Permis de travail",
      projectSourcing: "Sourcing",
      projectPartnership: "Partenariat",
      footerDescription: "Plateforme internationale d’opportunités : études, permis de travail, immobilier, commerce et sourcing.",
      explore: "Explorer",
      transparency: "Transparence",
      legal: "Mentions légales — à compléter",
      privacy: "Politique de confidentialité — à compléter",
      data: "Protection des données — à compléter",
    },
    homePage: {
      imageAlt: "Équipe internationale collaborant autour d’un projet global",
      heroEyebrow: "PLATEFORME INTERNATIONALE D’AFFAIRES ET D’OPPORTUNITÉS",
      heroTitle: "RELIER LES OPPORTUNITÉS. CONSTRUIRE DES AVENIRS MONDIAUX.",
      intro: "Une plateforme internationale dédiée aux études, au sourcing, à l’immobilier et au développement de projets.",
      studyCta: "ÉTUDIER À L’ÉTRANGER",
      sourcingCta: "SOURCING INTERNATIONAL",
      startEyebrow: "COMMENCEZ ICI",
      lookingFor: "QUE RECHERCHEZ-VOUS ?",
      selectIntro: "Choisissez votre point de départ. Chaque parcours mène aux informations utiles et, lorsque le service est disponible, à une demande encadrée par ICX.",
      explore: "EXPLORER",
      studyImageAlt: "Étudiants internationaux examinant leurs options d’études",
      studyEyebrow: "ORIENTATION INTERNATIONALE",
      studyTitle: "Votre projet d’études commence par des sources fiables.",
      studyBody: "Recherchez des établissements, consultez leurs sites officiels et organisez votre dossier. ICX n’est pas une université et ne revendique aucun partenariat non confirmé.",
      studyButton: "DÉCOUVRIR LE PARCOURS",
      journeyEyebrow: "UN PARCOURS SIMPLE ET GUIDÉ",
      journeyTitle: "Un parcours clair, de l’intention à l’action.",
      safety: "Aucune information sensible sans source.",
      timeline: [["01", "Exploration", "Pays, niveau, domaine, budget et langue."], ["02", "Sélection", "Consultez les sources officielles des établissements."], ["03", "Dossier ICX", "Créez votre espace et déposez les éléments demandés."], ["04", "Suivi", "Suivez les statuts et demandes de compléments."]],
      transparencyEyebrow: "TRANSPARENCE PAR CONCEPTION",
      transparencyTitle: "Des informations séparées, des décisions éclairées.",
      transparencyBody: "La plateforme distingue les établissements, leurs canaux officiels et l’accompagnement ICX. Les relations sont affichées avec un type vérifiable.",
      privacyTitle: "Confidentialité",
      privacyBody: "Accès contrôlé et stockage séparé pour les documents sensibles.",
      internationalTitle: "International",
      internationalBody: "Interface multilingue et prise en charge du sens de lecture RTL.",
      teamEyebrow: "NOTRE ÉQUIPE",
      teamTitle: "Une coordination humaine derrière chaque parcours.",
      teamBody: "Ces responsables assurent la gouvernance et la coordination de la plateforme ICX.",
      portrait: "Portrait de",
      operationsRole: "Responsable des opérations et de la coordination",
      operationsBody: "Coordination opérationnelle, suivi des parcours et organisation des échanges internationaux.",
      legalRole: "Responsable légal",
      legalBody: "Gouvernance, vision institutionnelle et développement responsable de la plateforme ICX.",
    },
    serviceCards: {
      study: ["Étudier à l’étranger", "Orientation internationale", "Orientation, admission et préparation administrative selon les sources officielles."],
      work: ["Permis de travail", "Roumanie et Pologne", "Assistance administrative pour travailler en Roumanie ou en Pologne."],
      sourcing: ["Sourcing international", "DealFlare et sourcing", "Structurez votre besoin et les étapes de recherche de fournisseurs."],
      realEstate: ["Opportunités immobilières", "Investissement et mobilité", "Préparez une recherche internationale sans annonce non vérifiée."],
      commerce: ["Commerce en ligne et affaires", "Croissance commerciale", "Un socle pour catalogues, devis et futures opérations commerciales."],
      partnership: ["Devenir partenaire", "Collaborations", "Présentez votre organisation pour une analyse responsable."],
      property: ["Mandats et projets", "Gestion des opportunités", "Un parcours de qualification pour vos projets et mises en relation."],
    },
    studyPage: {
      eyebrow: "ORIENTATION INTERNATIONALE", title: "Un parcours d’études fondé sur la clarté.", intro: "Définissez votre projet, découvrez des établissements et consultez leurs canaux officiels. ICX intervient dans les limites des services disponibles.", guided: "PARCOURS GUIDÉ",
      steps: ["Choisir une destination", "Préciser le niveau et le domaine", "Consulter les informations officielles", "Créer un dossier ICX", "Préparer les documents demandés", "Suivre l’avancement"],
      fileTitle: "Votre espace de dossier", fileBody: "Créez votre compte pour conserver vos préférences, construire votre demande et déposer les fichiers autorisés.", fileButton: "CRÉER MON DOSSIER",
      destinationsEyebrow: "DESTINATIONS À EXPLORER", destinationsTitle: "Commencez par votre destination.", universityButton: "RECHERCHER UNE UNIVERSITÉ",
      destinations: ["Roumanie", "France", "Allemagne", "Belgique", "Espagne", "Portugal", "Italie", "Pays-Bas", "Pologne", "Hongrie", "Irlande", "Suède", "Canada", "États-Unis", "Chine"],
      important: "Information importante", questions: "DES QUESTIONS AVANT DE COMMENCER ?", sourcesTitle: "Consultez d’abord les sources officielles.", ubb: "Admission internationale UBB", aaft: "Informations de l’association AAFT",
    },
    servicesPage: {
      eyebrow: "DEALFLARE ET SOURCING", title: "Des services conçus pour relier les bonnes opportunités.", intro: "La plateforme peut évoluer vers des espaces partenaires, catalogues et places de marché, sans activer de promesses ou d’opérations non validées.", access: "ACCÉDER AU PARCOURS", modularTitle: "Une plateforme modulaire, pas une vitrine figée.", features: ["Catalogues et demandes de devis", "Suivi des demandes et messages", "Fiches d’opportunités contrôlées", "Administration et rôles granulaires"],
    },
    sourcingPage: {
      imageAlt: "Professionnels examinant une solution logistique internationale", eyebrow: "DEALFLARE ET SOURCING", title: "Sourcing international.", intro: "Vous recherchez un produit, un fournisseur ou une solution ? Décrivez le besoin. ICX organise l’analyse sans garantir une offre, un prix ou un fournisseur avant validation.", steps: ["Demande reçue", "Analyse", "Recherche de fournisseurs", "Sélection et devis", "Négociation", "Validation et logistique"], requestEyebrow: "DEMANDE DE SOURCING", requestTitle: "Présentez votre besoin.", successTitle: "Votre demande est enregistrée.", successBody: "L’équipe pourra l’examiner dans l’espace de suivi. Ce formulaire ne crée aucun engagement commercial.", name: "Nom complet *", email: "Email professionnel *", organization: "Organisation", product: "Produit recherché *", quantity: "Quantité", budget: "Budget indicatif", origin: "Pays d’origine souhaité", destination: "Pays de destination", detail: "Description détaillée", detailPlaceholder: "Normes, certifications, délais, Incoterm ou informations utiles…", submit: "SOUMETTRE LA DEMANDE", error: "Une erreur est survenue. Vérifiez les champs et réessayez.",
    },
    partnershipPage: {
      eyebrow: "DÉVELOPPEZ UNE RELATION", title: "Devenir partenaire.", intro: "Présentez votre organisation et votre proposition. Toute demande est examinée avant de communiquer un statut de relation.", transparencyLabel: "Principe de transparence :", transparencyBody: "une organisation n’est jamais présentée comme partenaire officiel sans confirmation explicite et validation administrative.", successTitle: "Demande enregistrée.", successBody: "Votre proposition peut maintenant être attribuée à un responsable dans l’espace d’administration.", formEyebrow: "FORMULAIRE PROFESSIONNEL", name: "Nom *", email: "Email *", organization: "Organisation", type: "Type de partenaire", country: "Pays", city: "Ville", website: "Site web", proposal: "Présentation / proposition", proposalPlaceholder: "Activité, proposition, documents ou besoins de coopération…", submit: "SOUMETTRE LA DEMANDE", error: "Une erreur est survenue. Vérifiez les champs et réessayez.", types: ["Université", "École", "Entreprise", "Fournisseur", "Agence", "Investisseur", "Promoteur immobilier", "Institution", "Organisation", "Autre"],
    },
    partnersPage: {
      eyebrow: "ÉCOSYSTÈME ICX", title: "Partenaires et organisations.", intro: "Chaque fiche distingue son type de relation. La qualification est contrôlée par l’administration et n’est jamais déduite de sources publiques.", ruleTitle: "Règle de présentation des relations", ruleBody: "Aucune organisation ne doit être affichée comme partenaire officiel d’ICX POWER SOLUTIONS sans confirmation explicite. Le type de relation validé par l’administration fait foi.", collaboration: "NOUVELLE COLLABORATION", collaborationTitle: "Souhaitez-vous présenter votre organisation ?", become: "DEVENIR PARTENAIRE", visit: "VISITER LE SITE", explore: "CONSULTER LES INFORMATIONS", commercialPending: "Partenaire commercial — à confirmer", lorondo: "Son site public présente notamment des services de transport, d’expédition, de ressources humaines et de conseil.", association: "Association référencée", aaft: "AAFT est une association créée en Roumanie par Jean Lansana KOUNDOUNO et K Marcel TRAORE. Elle n’est pas une université et aucun partenariat ICX n’est présumé.",
    },
    dossierPage: {
      secure: "ESPACE SÉCURISÉ", loginTitle: "Connectez-vous pour accéder à votre dossier ICX.", loginBody: "Le dossier permet de sauvegarder votre projet, recevoir des statuts et transmettre les documents autorisés selon vos droits.", loginButton: "SE CONNECTER", hero: "MON DOSSIER ICX", title: "Votre projet, au même endroit.", intro: "Gérez vos demandes, consultez les étapes et transmettez les documents uniquement dans votre espace authentifié.", requests: "MES DEMANDES", current: "Dossiers en cours", newFile: "NOUVEAU DOSSIER", updated: "Mis à jour le", emptyTitle: "Aucun dossier pour le moment.", emptyBody: "Commencez par créer une demande d’orientation.", secureDocuments: "DOCUMENTS SÉCURISÉS", authenticated: "Espace authentifié", add: "AJOUTER", uploading: "Téléversement sécurisé en cours…", newRequest: "NOUVELLE DEMANDE", destination: "Destination *", level: "Niveau d’étude *", field: "Domaine souhaité *", budget: "Budget indicatif", language: "Langue préférée", note: "Note pour l’équipe ICX", creating: "CRÉATION…", create: "CRÉER LE DOSSIER", cancel: "ANNULER", fileError: "Formats autorisés : PDF, JPG, PNG. Taille maximale : 4 Mo.", loadError: "Impossible de charger vos dossiers. Réessayez.", createError: "Impossible de créer le dossier. Vérifiez les champs.", uploadError: "Le téléversement a échoué. Réessayez.", statuses: { DRAFT: "Brouillon", RECEIVED: "Dossier reçu", VERIFICATION: "Vérification", MISSING_DOCUMENTS: "Documents manquants", COMPLETE: "Dossier complet", SUBMISSION: "Transmission", PENDING_RESPONSE: "En attente de réponse", ADMITTED: "Admis", NOT_ADMITTED: "Non admis" }, documents: { passport: "Passeport", national_id: "Carte d’identité", diploma: "Diplôme", transcript: "Relevé de notes", cv: "CV", motivation_letter: "Lettre de motivation", photo: "Photo", language_certificate: "Certificat linguistique", financial_proof: "Preuve financière", recommendation_letter: "Lettre de recommandation", other: "Autre" }, validations: { pending: "En attente", accepted: "Accepté", rejected: "Refusé" },
    },
    institutionPage: { unavailable: "Fiche indisponible", unavailableBody: "Cette institution est peut-être en cours de vérification.", back: "RETOUR AU RÉPERTOIRE", directory: "RÉPERTOIRE DES UNIVERSITÉS", presentation: "PRÉSENTATION", publicInfo: "INFORMATIONS PUBLIQUES", country: "Pays", city: "Ville", programmes: "Programmes / niveaux", languages: "Langues", visit: "VISITER LE SITE OFFICIEL", admission: "VOIR L’ADMISSION", submit: "DÉPOSER MON DOSSIER VIA ICX" },
    universitiesPage: { noResults: "Aucun établissement trouvé." },
    workPage: { guidanceTitle: "Un accompagnement documenté, étape par étape.", guidanceBody: "ICX oriente vers les sources officielles et aide à préparer les démarches administratives liées à un projet professionnel en Roumanie ou en Pologne.", steps: ["Analyse du profil et du projet professionnel", "Orientation vers les sources et autorités officielles", "Préparation selon les documents demandés", "Suivi sans promesse de résultat"], romania: "Roumanie", romaniaNote: "Informations officielles de l’Inspectorat général pour l’immigration.", poland: "Pologne", polandNote: "Informations officielles de l’Office polonais des étrangers.", mobilityTitle: "Vous avez un projet de mobilité professionnelle ?", mobilityBody: "Présentez votre situation, votre métier, votre pays de résidence et votre objectif. Les demandes sont étudiées selon les services disponibles.", mobilityButton: "DÉCRIRE MON PROJET" },
    disclosure: "ICX POWER SOLUTIONS accompagne les candidats en orientation, admission et assistance administrative selon les services disponibles. Les critères, frais, délais, décisions et permis relèvent des établissements et autorités concernés et doivent être confirmés auprès de leurs sources officielles.",
    institutionMeta: { relation: "Institution référencée", summary: "Cette institution est référencée afin d’orienter les candidats vers ses informations officielles.", verified: "Source officielle consultée — à revalider avant toute candidature.", programmes: "Programmes à consulter sur le site officiel", languages: "À consulter par programme" },
  },
  en: {
    layout: { homeAria: "ICX POWER SOLUTIONS home", navAria: "Main navigation", theme: "Change theme", language: "Choose language", openMenu: "Open menu", closeMenu: "Close menu", backToTop: "Back to top", projectStudy: "Study", projectWork: "Work permits", projectSourcing: "Sourcing", projectPartnership: "Partnership", footerDescription: "International opportunity platform for study, work permits, real estate, commerce and sourcing.", explore: "Explore", transparency: "Transparency", legal: "Legal notice — to be completed", privacy: "Privacy policy — to be completed", data: "Data protection — to be completed" },
    homePage: { imageAlt: "International team collaborating on a global project", heroEyebrow: "INTERNATIONAL BUSINESS AND OPPORTUNITY PLATFORM", heroTitle: "CONNECTING OPPORTUNITIES. BUILDING GLOBAL FUTURES.", intro: "An international platform for study, sourcing, real estate and project development.", studyCta: "STUDY ABROAD", sourcingCta: "INTERNATIONAL SOURCING", startEyebrow: "START HERE", lookingFor: "WHAT ARE YOU LOOKING FOR?", selectIntro: "Choose a starting point. Each journey leads to useful information and, where available, a request managed by ICX.", explore: "EXPLORE", studyImageAlt: "International students reviewing study options", studyEyebrow: "INTERNATIONAL GUIDANCE", studyTitle: "Your study project starts with reliable sources.", studyBody: "Find institutions, consult their official websites and organise your file. ICX is not a university and claims no unconfirmed partnership.", studyButton: "DISCOVER THE JOURNEY", journeyEyebrow: "A SIMPLE, GUIDED JOURNEY", journeyTitle: "A clear path from intention to action.", safety: "No sensitive information without a source.", timeline: [["01", "Explore", "Country, level, subject, budget and language."], ["02", "Select", "Consult official institution sources."], ["03", "ICX file", "Create your space and provide requested items."], ["04", "Follow up", "Track statuses and requests for more information."]], transparencyEyebrow: "TRANSPARENCY BY DESIGN", transparencyTitle: "Separate information for informed decisions.", transparencyBody: "The platform distinguishes institutions, official channels and ICX support. Relationships are displayed with a verifiable type.", privacyTitle: "Privacy", privacyBody: "Controlled access and separate storage for sensitive documents.", internationalTitle: "International", internationalBody: "Multilingual interface with right-to-left support.", teamEyebrow: "OUR TEAM", teamTitle: "Human coordination behind every journey.", teamBody: "These leaders oversee governance and coordination of the ICX platform.", portrait: "Portrait of", operationsRole: "Head of operations and coordination", operationsBody: "Operational coordination, journey monitoring and organisation of international exchanges.", legalRole: "Legal representative", legalBody: "Governance, institutional vision and responsible development of the ICX platform." },
    serviceCards: { study: ["Study abroad", "International guidance", "Guidance, admissions and administrative preparation based on official sources."], work: ["Work permits", "Romania and Poland", "Administrative assistance for working in Romania or Poland."], sourcing: ["International sourcing", "DealFlare and sourcing", "Structure your needs and supplier search stages."], realEstate: ["Real estate opportunities", "Investment and mobility", "Prepare an international search without unverified listings."], commerce: ["E-commerce and business", "Commercial growth", "A foundation for catalogues, quotations and future commerce."], partnership: ["Become a partner", "Collaboration", "Present your organisation for responsible review."], property: ["Mandates and projects", "Opportunity management", "A qualification journey for projects and introductions."] },
    studyPage: { eyebrow: "INTERNATIONAL GUIDANCE", title: "A study journey built on clarity.", intro: "Define your project, discover institutions and consult their official channels. ICX acts within the limits of available services.", guided: "GUIDED JOURNEY", steps: ["Choose a destination", "Define the level and subject", "Consult official information", "Create an ICX file", "Prepare requested documents", "Track progress"], fileTitle: "Your file space", fileBody: "Create an account to save preferences, build your request and upload authorised files.", fileButton: "CREATE MY FILE", destinationsEyebrow: "DESTINATIONS TO EXPLORE", destinationsTitle: "Start with your destination.", universityButton: "FIND A UNIVERSITY", destinations: ["Romania", "France", "Germany", "Belgium", "Spain", "Portugal", "Italy", "Netherlands", "Poland", "Hungary", "Ireland", "Sweden", "Canada", "United States", "China"], important: "Important information", questions: "QUESTIONS BEFORE YOU START?", sourcesTitle: "Consult official sources first.", ubb: "UBB international admissions", aaft: "AAFT association information" },
    servicesPage: { eyebrow: "DEALFLARE AND SOURCING", title: "Services designed to connect the right opportunities.", intro: "The platform can grow into partner spaces, catalogues and marketplaces without enabling unvalidated promises or operations.", access: "OPEN THIS JOURNEY", modularTitle: "A modular platform, not a static showcase.", features: ["Catalogues and quotation requests", "Request and message tracking", "Controlled opportunity profiles", "Administration and granular roles"] },
    sourcingPage: { imageAlt: "Professionals reviewing an international logistics solution", eyebrow: "DEALFLARE AND SOURCING", title: "International sourcing.", intro: "Looking for a product, supplier or solution? Describe your needs. ICX organises the review without guaranteeing an offer, price or supplier before validation.", steps: ["Request received", "Analysis", "Supplier research", "Selection and quotations", "Negotiation", "Validation and logistics"], requestEyebrow: "SOURCING REQUEST", requestTitle: "Describe your needs.", successTitle: "Your request has been recorded.", successBody: "The team can review it in the tracking space. This form creates no commercial commitment.", name: "Full name *", email: "Business email *", organization: "Organisation", product: "Product required *", quantity: "Quantity", budget: "Indicative budget", origin: "Preferred country of origin", destination: "Destination country", detail: "Detailed description", detailPlaceholder: "Standards, certifications, deadlines, Incoterm or useful information…", submit: "SUBMIT REQUEST", error: "An error occurred. Check the fields and try again." },
    partnershipPage: { eyebrow: "DEVELOP A RELATIONSHIP", title: "Become a partner.", intro: "Present your organisation and proposal. Every request is reviewed before any relationship status is communicated.", transparencyLabel: "Transparency principle:", transparencyBody: "an organisation is never presented as an official partner without explicit confirmation and administrative validation.", successTitle: "Request recorded.", successBody: "Your proposal can now be assigned to a manager in the administration space.", formEyebrow: "PROFESSIONAL FORM", name: "Name *", email: "Email *", organization: "Organisation", type: "Partner type", country: "Country", city: "City", website: "Website", proposal: "Presentation / proposal", proposalPlaceholder: "Activity, proposal, documents or cooperation needs…", submit: "SUBMIT REQUEST", error: "An error occurred. Check the fields and try again.", types: ["University", "School", "Company", "Supplier", "Agency", "Investor", "Property developer", "Institution", "Organisation", "Other"] },
    partnersPage: { eyebrow: "ICX ECOSYSTEM", title: "Partners and organisations.", intro: "Each profile states its relationship type. Classification is controlled by administration and is never inferred from public sources.", ruleTitle: "Relationship display rule", ruleBody: "No organisation may be shown as an official ICX POWER SOLUTIONS partner without explicit confirmation. The relationship type validated by administration is authoritative.", collaboration: "NEW COLLABORATION", collaborationTitle: "Would you like to present your organisation?", become: "BECOME A PARTNER", visit: "VISIT WEBSITE", explore: "VIEW INFORMATION", commercialPending: "Commercial partner — confirmation pending", lorondo: "Its public website describes transport, shipping, human resources and consulting services.", association: "Listed association", aaft: "AAFT is an association created in Romania by Jean Lansana KOUNDOUNO and K Marcel TRAORE. It is not a university, and no ICX partnership is presumed." },
    dossierPage: { secure: "SECURE SPACE", loginTitle: "Sign in to access your ICX file.", loginBody: "The file lets you save your project, receive statuses and send authorised documents according to your access rights.", loginButton: "SIGN IN", hero: "MY ICX FILE", title: "Your project in one place.", intro: "Manage requests, review stages and send documents only through your authenticated space.", requests: "MY REQUESTS", current: "Current files", newFile: "NEW FILE", updated: "Updated on", emptyTitle: "No file yet.", emptyBody: "Start by creating a guidance request.", secureDocuments: "SECURE DOCUMENTS", authenticated: "Authenticated space", add: "ADD", uploading: "Secure upload in progress…", newRequest: "NEW REQUEST", destination: "Destination *", level: "Study level *", field: "Preferred subject *", budget: "Indicative budget", language: "Preferred language", note: "Note for the ICX team", creating: "CREATING…", create: "CREATE FILE", cancel: "CANCEL", fileError: "Allowed formats: PDF, JPG, PNG. Maximum size: 4 MB.", loadError: "Unable to load your files. Try again.", createError: "Unable to create the file. Check the fields.", uploadError: "Upload failed. Try again.", statuses: { DRAFT: "Draft", RECEIVED: "File received", VERIFICATION: "Verification", MISSING_DOCUMENTS: "Missing documents", COMPLETE: "File complete", SUBMISSION: "Submission", PENDING_RESPONSE: "Awaiting response", ADMITTED: "Admitted", NOT_ADMITTED: "Not admitted" }, documents: { passport: "Passport", national_id: "National ID", diploma: "Diploma", transcript: "Transcript", cv: "CV", motivation_letter: "Motivation letter", photo: "Photo", language_certificate: "Language certificate", financial_proof: "Financial proof", recommendation_letter: "Recommendation letter", other: "Other" }, validations: { pending: "Pending", accepted: "Accepted", rejected: "Rejected" } },
    institutionPage: { unavailable: "Profile unavailable", unavailableBody: "This institution may still be under review.", back: "BACK TO DIRECTORY", directory: "UNIVERSITY DIRECTORY", presentation: "OVERVIEW", publicInfo: "PUBLIC INFORMATION", country: "Country", city: "City", programmes: "Programmes / levels", languages: "Languages", visit: "VISIT OFFICIAL WEBSITE", admission: "VIEW ADMISSIONS", submit: "SUBMIT MY FILE THROUGH ICX" }, universitiesPage: { noResults: "No institution found." },
    workPage: { guidanceTitle: "Documented support, step by step.", guidanceBody: "ICX directs applicants to official sources and assists with administrative preparation for professional projects in Romania or Poland.", steps: ["Profile and professional project analysis", "Guidance to official sources and authorities", "Preparation based on required documents", "Follow-up without any outcome guarantee"], romania: "Romania", romaniaNote: "Official information from the General Inspectorate for Immigration.", poland: "Poland", polandNote: "Official information from the Polish Office for Foreigners.", mobilityTitle: "Do you have a professional mobility project?", mobilityBody: "Describe your situation, occupation, country of residence and goal. Requests are reviewed according to available services.", mobilityButton: "DESCRIBE MY PROJECT" },
    disclosure: "ICX POWER SOLUTIONS supports candidates with guidance, admissions and administrative assistance according to available services. Criteria, fees, timescales, decisions and permits remain the responsibility of the relevant institutions and authorities and must be confirmed through official sources.", institutionMeta: { relation: "Listed institution", summary: "This institution is listed to direct candidates to its official information.", verified: "Official source consulted — verify again before applying.", programmes: "See programmes on the official website", languages: "Check for each programme" },
  },
  ro: {
    layout: { homeAria: "Pagina principală ICX POWER SOLUTIONS", navAria: "Navigare principală", theme: "Schimbă tema", language: "Alege limba", openMenu: "Deschide meniul", closeMenu: "Închide meniul", backToTop: "Înapoi sus", projectStudy: "Studii", projectWork: "Permise de muncă", projectSourcing: "Aprovizionare", projectPartnership: "Parteneriat", footerDescription: "Platformă internațională pentru studii, permise de muncă, imobiliare, comerț și aprovizionare.", explore: "Explorează", transparency: "Transparență", legal: "Mențiuni legale — de completat", privacy: "Politica de confidențialitate — de completat", data: "Protecția datelor — de completat" },
    homePage: { imageAlt: "Echipă internațională colaborând la un proiect global", heroEyebrow: "PLATFORMĂ INTERNAȚIONALĂ DE AFACERI ȘI OPORTUNITĂȚI", heroTitle: "CONECTĂM OPORTUNITĂȚI. CONSTRUIM VIITORURI GLOBALE.", intro: "O platformă internațională pentru studii, aprovizionare, imobiliare și dezvoltarea proiectelor.", studyCta: "STUDII ÎN STRĂINĂTATE", sourcingCta: "APROVIZIONARE INTERNAȚIONALĂ", startEyebrow: "ÎNCEPE AICI", lookingFor: "CE CAUȚI?", selectIntro: "Alege punctul de plecare. Fiecare parcurs conduce la informații utile și, dacă serviciul este disponibil, la o cerere gestionată de ICX.", explore: "EXPLOREAZĂ", studyImageAlt: "Studenți internaționali analizând opțiuni de studiu", studyEyebrow: "ORIENTARE INTERNAȚIONALĂ", studyTitle: "Proiectul tău de studii începe cu surse de încredere.", studyBody: "Caută instituții, consultă site-urile oficiale și organizează dosarul. ICX nu este universitate și nu pretinde parteneriate neconfirmate.", studyButton: "DESCOPERĂ PARCURSUL", journeyEyebrow: "UN PARCURS SIMPLU ȘI GHIDAT", journeyTitle: "Un drum clar de la intenție la acțiune.", safety: "Nicio informație sensibilă fără sursă.", timeline: [["01", "Explorare", "Țară, nivel, domeniu, buget și limbă."], ["02", "Selecție", "Consultă sursele oficiale ale instituțiilor."], ["03", "Dosar ICX", "Creează spațiul și depune elementele solicitate."], ["04", "Urmărire", "Urmărește stările și cererile de completare."]], transparencyEyebrow: "TRANSPARENȚĂ PRIN CONCEPȚIE", transparencyTitle: "Informații separate pentru decizii informate.", transparencyBody: "Platforma separă instituțiile, canalele oficiale și asistența ICX. Relațiile au un tip verificabil.", privacyTitle: "Confidențialitate", privacyBody: "Acces controlat și stocare separată pentru documentele sensibile.", internationalTitle: "Internațional", internationalBody: "Interfață multilingvă cu suport pentru scriere de la dreapta la stânga.", teamEyebrow: "ECHIPA NOASTRĂ", teamTitle: "Coordonare umană în spatele fiecărui parcurs.", teamBody: "Acești responsabili asigură guvernanța și coordonarea platformei ICX.", portrait: "Portretul lui", operationsRole: "Responsabil operațiuni și coordonare", operationsBody: "Coordonare operațională, urmărirea parcursurilor și organizarea schimburilor internaționale.", legalRole: "Reprezentant legal", legalBody: "Guvernanță, viziune instituțională și dezvoltarea responsabilă a platformei ICX." },
    serviceCards: { study: ["Studii în străinătate", "Orientare internațională", "Orientare, admitere și pregătire administrativă pe baza surselor oficiale."], work: ["Permise de muncă", "România și Polonia", "Asistență administrativă pentru munca în România sau Polonia."], sourcing: ["Aprovizionare internațională", "DealFlare și aprovizionare", "Structurează nevoia și etapele căutării furnizorilor."], realEstate: ["Oportunități imobiliare", "Investiții și mobilitate", "Pregătește o căutare internațională fără anunțuri neverificate."], commerce: ["Comerț electronic și afaceri", "Creștere comercială", "O bază pentru cataloage, oferte și operațiuni viitoare."], partnership: ["Devino partener", "Colaborări", "Prezintă organizația pentru o analiză responsabilă."], property: ["Mandate și proiecte", "Gestionarea oportunităților", "Un parcurs de calificare pentru proiecte și puneri în legătură."] },
    studyPage: { eyebrow: "ORIENTARE INTERNAȚIONALĂ", title: "Un parcurs de studii bazat pe claritate.", intro: "Definește proiectul, descoperă instituții și consultă canalele lor oficiale. ICX acționează în limita serviciilor disponibile.", guided: "PARCURS GHIDAT", steps: ["Alege o destinație", "Precizează nivelul și domeniul", "Consultă informațiile oficiale", "Creează un dosar ICX", "Pregătește documentele solicitate", "Urmărește progresul"], fileTitle: "Spațiul dosarului tău", fileBody: "Creează un cont pentru a salva preferințele, pregăti cererea și încărca fișierele autorizate.", fileButton: "CREEAZĂ DOSARUL", destinationsEyebrow: "DESTINAȚII DE EXPLORAT", destinationsTitle: "Începe cu destinația.", universityButton: "CAUTĂ O UNIVERSITATE", destinations: ["România", "Franța", "Germania", "Belgia", "Spania", "Portugalia", "Italia", "Țările de Jos", "Polonia", "Ungaria", "Irlanda", "Suedia", "Canada", "Statele Unite", "China"], important: "Informație importantă", questions: "ÎNTREBĂRI ÎNAINTE DE ÎNCEPERE?", sourcesTitle: "Consultă mai întâi sursele oficiale.", ubb: "Admitere internațională UBB", aaft: "Informații despre asociația AAFT" },
    servicesPage: { eyebrow: "DEALFLARE ȘI APROVIZIONARE", title: "Servicii create pentru a conecta oportunitățile potrivite.", intro: "Platforma poate evolua spre spații pentru parteneri, cataloage și piețe, fără promisiuni sau operațiuni nevalidate.", access: "DESCHIDE PARCURSUL", modularTitle: "O platformă modulară, nu o vitrină statică.", features: ["Cataloage și cereri de ofertă", "Urmărirea cererilor și mesajelor", "Fișe de oportunități controlate", "Administrare și roluri granulare"] },
    sourcingPage: { imageAlt: "Profesioniști analizând o soluție logistică internațională", eyebrow: "DEALFLARE ȘI APROVIZIONARE", title: "Aprovizionare internațională.", intro: "Cauți un produs, furnizor sau o soluție? Descrie nevoia. ICX organizează analiza fără a garanta o ofertă, un preț sau un furnizor înainte de validare.", steps: ["Cerere primită", "Analiză", "Căutare furnizori", "Selecție și oferte", "Negociere", "Validare și logistică"], requestEyebrow: "CERERE DE APROVIZIONARE", requestTitle: "Prezintă nevoia.", successTitle: "Cererea a fost înregistrată.", successBody: "Echipa o poate analiza în spațiul de urmărire. Formularul nu creează un angajament comercial.", name: "Nume complet *", email: "E-mail profesional *", organization: "Organizație", product: "Produs căutat *", quantity: "Cantitate", budget: "Buget orientativ", origin: "Țara de origine preferată", destination: "Țara de destinație", detail: "Descriere detaliată", detailPlaceholder: "Standarde, certificări, termene, Incoterm sau informații utile…", submit: "TRIMITE CEREREA", error: "A apărut o eroare. Verifică câmpurile și încearcă din nou." },
    partnershipPage: { eyebrow: "DEZVOLTĂ O RELAȚIE", title: "Devino partener.", intro: "Prezintă organizația și propunerea. Fiecare cerere este analizată înainte de comunicarea unui statut al relației.", transparencyLabel: "Principiu de transparență:", transparencyBody: "o organizație nu este prezentată niciodată ca partener oficial fără confirmare explicită și validare administrativă.", successTitle: "Cerere înregistrată.", successBody: "Propunerea poate fi atribuită unui responsabil în spațiul de administrare.", formEyebrow: "FORMULAR PROFESIONAL", name: "Nume *", email: "E-mail *", organization: "Organizație", type: "Tip de partener", country: "Țară", city: "Oraș", website: "Site web", proposal: "Prezentare / propunere", proposalPlaceholder: "Activitate, propunere, documente sau nevoi de cooperare…", submit: "TRIMITE CEREREA", error: "A apărut o eroare. Verifică câmpurile și încearcă din nou.", types: ["Universitate", "Școală", "Companie", "Furnizor", "Agenție", "Investitor", "Dezvoltator imobiliar", "Instituție", "Organizație", "Altul"] },
    partnersPage: { eyebrow: "ECOSISTEM ICX", title: "Parteneri și organizații.", intro: "Fiecare fișă precizează tipul relației. Clasificarea este controlată de administrație și nu este dedusă din surse publice.", ruleTitle: "Regula de afișare a relațiilor", ruleBody: "Nicio organizație nu poate fi afișată ca partener oficial ICX POWER SOLUTIONS fără confirmare explicită. Tipul validat de administrație este referința.", collaboration: "COLABORARE NOUĂ", collaborationTitle: "Dorești să prezinți organizația ta?", become: "DEVINO PARTENER", visit: "VIZITEAZĂ SITE-UL", explore: "VEZI INFORMAȚIILE", commercialPending: "Partener comercial — confirmare în așteptare", lorondo: "Site-ul său public prezintă servicii de transport, expediție, resurse umane și consultanță.", association: "Asociație listată", aaft: "AAFT este o asociație creată în România de Jean Lansana KOUNDOUNO și K Marcel TRAORE. Nu este universitate și nu se presupune un parteneriat ICX." },
    dossierPage: { secure: "SPAȚIU SECURIZAT", loginTitle: "Autentifică-te pentru a accesa dosarul ICX.", loginBody: "Dosarul permite salvarea proiectului, primirea stărilor și transmiterea documentelor autorizate conform drepturilor tale.", loginButton: "AUTENTIFICARE", hero: "DOSARUL MEU ICX", title: "Proiectul tău într-un singur loc.", intro: "Gestionează cererile, consultă etapele și trimite documente numai în spațiul autentificat.", requests: "CERERILE MELE", current: "Dosare în curs", newFile: "DOSAR NOU", updated: "Actualizat la", emptyTitle: "Niciun dosar momentan.", emptyBody: "Începe prin crearea unei cereri de orientare.", secureDocuments: "DOCUMENTE SECURIZATE", authenticated: "Spațiu autentificat", add: "ADAUGĂ", uploading: "Încărcare securizată în curs…", newRequest: "CERERE NOUĂ", destination: "Destinație *", level: "Nivel de studiu *", field: "Domeniu dorit *", budget: "Buget orientativ", language: "Limba preferată", note: "Notă pentru echipa ICX", creating: "SE CREEAZĂ…", create: "CREEAZĂ DOSARUL", cancel: "ANULEAZĂ", fileError: "Formate permise: PDF, JPG, PNG. Dimensiune maximă: 4 MB.", loadError: "Dosarele nu au putut fi încărcate. Încearcă din nou.", createError: "Dosarul nu a putut fi creat. Verifică câmpurile.", uploadError: "Încărcarea a eșuat. Încearcă din nou.", statuses: { DRAFT: "Ciornă", RECEIVED: "Dosar primit", VERIFICATION: "Verificare", MISSING_DOCUMENTS: "Documente lipsă", COMPLETE: "Dosar complet", SUBMISSION: "Transmitere", PENDING_RESPONSE: "În așteptarea răspunsului", ADMITTED: "Admis", NOT_ADMITTED: "Neadmis" }, documents: { passport: "Pașaport", national_id: "Carte de identitate", diploma: "Diplomă", transcript: "Foaie matricolă", cv: "CV", motivation_letter: "Scrisoare de motivație", photo: "Fotografie", language_certificate: "Certificat lingvistic", financial_proof: "Dovadă financiară", recommendation_letter: "Scrisoare de recomandare", other: "Altul" }, validations: { pending: "În așteptare", accepted: "Acceptat", rejected: "Respins" } },
    institutionPage: { unavailable: "Fișă indisponibilă", unavailableBody: "Această instituție poate fi încă în curs de verificare.", back: "ÎNAPOI LA DIRECTOR", directory: "DIRECTORUL UNIVERSITĂȚILOR", presentation: "PREZENTARE", publicInfo: "INFORMAȚII PUBLICE", country: "Țară", city: "Oraș", programmes: "Programe / niveluri", languages: "Limbi", visit: "VIZITEAZĂ SITE-UL OFICIAL", admission: "VEZI ADMITEREA", submit: "DEPUNE DOSARUL PRIN ICX" }, universitiesPage: { noResults: "Nu a fost găsită nicio instituție." },
    workPage: { guidanceTitle: "Asistență documentată, pas cu pas.", guidanceBody: "ICX îndrumă spre sursele oficiale și ajută la pregătirea administrativă pentru proiecte profesionale în România sau Polonia.", steps: ["Analiza profilului și proiectului profesional", "Orientare spre surse și autorități oficiale", "Pregătire conform documentelor solicitate", "Urmărire fără promisiunea rezultatului"], romania: "România", romaniaNote: "Informații oficiale ale Inspectoratului General pentru Imigrări.", poland: "Polonia", polandNote: "Informații oficiale ale Oficiului polonez pentru Străini.", mobilityTitle: "Ai un proiect de mobilitate profesională?", mobilityBody: "Prezintă situația, profesia, țara de reședință și obiectivul. Cererile sunt analizate conform serviciilor disponibile.", mobilityButton: "DESCRIE PROIECTUL" },
    disclosure: "ICX POWER SOLUTIONS sprijină candidații prin orientare, admitere și asistență administrativă, în funcție de serviciile disponibile. Criteriile, taxele, termenele, deciziile și permisele aparțin instituțiilor și autorităților competente și trebuie confirmate din surse oficiale.", institutionMeta: { relation: "Instituție listată", summary: "Această instituție este listată pentru a îndruma candidații spre informațiile sale oficiale.", verified: "Sursă oficială consultată — verifică din nou înainte de candidatură.", programmes: "Consultă programele pe site-ul oficial", languages: "De verificat pentru fiecare program" },
  },
  pt: {
    layout: { homeAria: "Início ICX POWER SOLUTIONS", navAria: "Navegação principal", theme: "Alterar tema", language: "Escolher idioma", openMenu: "Abrir menu", closeMenu: "Fechar menu", backToTop: "Voltar ao topo", projectStudy: "Estudos", projectWork: "Permissões de trabalho", projectSourcing: "Aprovisionamento", projectPartnership: "Parceria", footerDescription: "Plataforma internacional para estudos, permissões de trabalho, imóveis, comércio e aprovisionamento.", explore: "Explorar", transparency: "Transparência", legal: "Aviso legal — a completar", privacy: "Política de privacidade — a completar", data: "Proteção de dados — a completar" },
    homePage: { imageAlt: "Equipa internacional a colaborar num projeto global", heroEyebrow: "PLATAFORMA INTERNACIONAL DE NEGÓCIOS E OPORTUNIDADES", heroTitle: "LIGAMOS OPORTUNIDADES. CONSTRUÍMOS FUTUROS GLOBAIS.", intro: "Uma plataforma internacional para estudos, aprovisionamento, imóveis e desenvolvimento de projetos.", studyCta: "ESTUDAR NO EXTERIOR", sourcingCta: "APROVISIONAMENTO INTERNACIONAL", startEyebrow: "COMECE AQUI", lookingFor: "O QUE PROCURA?", selectIntro: "Escolha o ponto de partida. Cada percurso conduz a informações úteis e, quando disponível, a um pedido gerido pela ICX.", explore: "EXPLORAR", studyImageAlt: "Estudantes internacionais a analisar opções de estudo", studyEyebrow: "ORIENTAÇÃO INTERNACIONAL", studyTitle: "O seu projeto de estudos começa com fontes fiáveis.", studyBody: "Pesquise instituições, consulte os sites oficiais e organize o dossiê. A ICX não é uma universidade e não reivindica parcerias não confirmadas.", studyButton: "DESCOBRIR O PERCURSO", journeyEyebrow: "UM PERCURSO SIMPLES E ORIENTADO", journeyTitle: "Um caminho claro da intenção à ação.", safety: "Nenhuma informação sensível sem fonte.", timeline: [["01", "Exploração", "País, nível, área, orçamento e idioma."], ["02", "Seleção", "Consulte as fontes oficiais das instituições."], ["03", "Dossiê ICX", "Crie o seu espaço e envie os elementos pedidos."], ["04", "Acompanhamento", "Acompanhe estados e pedidos de informação."]], transparencyEyebrow: "TRANSPARÊNCIA DESDE A CONCEÇÃO", transparencyTitle: "Informações separadas para decisões esclarecidas.", transparencyBody: "A plataforma distingue instituições, canais oficiais e apoio ICX. As relações têm um tipo verificável.", privacyTitle: "Privacidade", privacyBody: "Acesso controlado e armazenamento separado para documentos sensíveis.", internationalTitle: "Internacional", internationalBody: "Interface multilingue com suporte para leitura da direita para a esquerda.", teamEyebrow: "A NOSSA EQUIPA", teamTitle: "Coordenação humana por detrás de cada percurso.", teamBody: "Estes responsáveis asseguram a governação e coordenação da plataforma ICX.", portrait: "Retrato de", operationsRole: "Responsável de operações e coordenação", operationsBody: "Coordenação operacional, acompanhamento dos percursos e organização das relações internacionais.", legalRole: "Responsável legal", legalBody: "Governação, visão institucional e desenvolvimento responsável da plataforma ICX." },
    serviceCards: { study: ["Estudar no exterior", "Orientação internacional", "Orientação, admissão e preparação administrativa com fontes oficiais."], work: ["Permissões de trabalho", "Roménia e Polónia", "Assistência administrativa para trabalhar na Roménia ou Polónia."], sourcing: ["Aprovisionamento internacional", "DealFlare e aprovisionamento", "Estruture a necessidade e as etapas da pesquisa de fornecedores."], realEstate: ["Oportunidades imobiliárias", "Investimento e mobilidade", "Prepare uma pesquisa internacional sem anúncios não verificados."], commerce: ["Comércio eletrónico e negócios", "Crescimento comercial", "Uma base para catálogos, orçamentos e operações futuras."], partnership: ["Tornar-se parceiro", "Colaborações", "Apresente a organização para uma análise responsável."], property: ["Mandatos e projetos", "Gestão de oportunidades", "Um percurso de qualificação para projetos e contactos."] },
    studyPage: { eyebrow: "ORIENTAÇÃO INTERNACIONAL", title: "Um percurso de estudos baseado na clareza.", intro: "Defina o projeto, descubra instituições e consulte os canais oficiais. A ICX atua dentro dos serviços disponíveis.", guided: "PERCURSO ORIENTADO", steps: ["Escolher um destino", "Definir o nível e a área", "Consultar informações oficiais", "Criar um dossiê ICX", "Preparar os documentos pedidos", "Acompanhar o progresso"], fileTitle: "O espaço do seu dossiê", fileBody: "Crie uma conta para guardar preferências, preparar o pedido e enviar ficheiros autorizados.", fileButton: "CRIAR O MEU DOSSIÊ", destinationsEyebrow: "DESTINOS A EXPLORAR", destinationsTitle: "Comece pelo destino.", universityButton: "PROCURAR UMA UNIVERSIDADE", destinations: ["Roménia", "França", "Alemanha", "Bélgica", "Espanha", "Portugal", "Itália", "Países Baixos", "Polónia", "Hungria", "Irlanda", "Suécia", "Canadá", "Estados Unidos", "China"], important: "Informação importante", questions: "QUESTÕES ANTES DE COMEÇAR?", sourcesTitle: "Consulte primeiro as fontes oficiais.", ubb: "Admissão internacional UBB", aaft: "Informações da associação AAFT" },
    servicesPage: { eyebrow: "DEALFLARE E APROVISIONAMENTO", title: "Serviços concebidos para ligar as oportunidades certas.", intro: "A plataforma pode evoluir para espaços de parceiros, catálogos e mercados sem ativar promessas ou operações não validadas.", access: "ABRIR O PERCURSO", modularTitle: "Uma plataforma modular, não uma montra estática.", features: ["Catálogos e pedidos de orçamento", "Acompanhamento de pedidos e mensagens", "Fichas de oportunidades controladas", "Administração e funções granulares"] },
    sourcingPage: { imageAlt: "Profissionais a analisar uma solução logística internacional", eyebrow: "DEALFLARE E APROVISIONAMENTO", title: "Aprovisionamento internacional.", intro: "Procura um produto, fornecedor ou solução? Descreva a necessidade. A ICX organiza a análise sem garantir oferta, preço ou fornecedor antes da validação.", steps: ["Pedido recebido", "Análise", "Pesquisa de fornecedores", "Seleção e orçamentos", "Negociação", "Validação e logística"], requestEyebrow: "PEDIDO DE APROVISIONAMENTO", requestTitle: "Apresente a sua necessidade.", successTitle: "O pedido foi registado.", successBody: "A equipa poderá analisá-lo no espaço de acompanhamento. Este formulário não cria qualquer compromisso comercial.", name: "Nome completo *", email: "E-mail profissional *", organization: "Organização", product: "Produto procurado *", quantity: "Quantidade", budget: "Orçamento indicativo", origin: "País de origem preferido", destination: "País de destino", detail: "Descrição detalhada", detailPlaceholder: "Normas, certificações, prazos, Incoterm ou informações úteis…", submit: "ENVIAR PEDIDO", error: "Ocorreu um erro. Verifique os campos e tente novamente." },
    partnershipPage: { eyebrow: "DESENVOLVA UMA RELAÇÃO", title: "Tornar-se parceiro.", intro: "Apresente a organização e proposta. Cada pedido é analisado antes da comunicação de qualquer estatuto da relação.", transparencyLabel: "Princípio de transparência:", transparencyBody: "uma organização nunca é apresentada como parceira oficial sem confirmação explícita e validação administrativa.", successTitle: "Pedido registado.", successBody: "A proposta pode agora ser atribuída a um responsável no espaço de administração.", formEyebrow: "FORMULÁRIO PROFISSIONAL", name: "Nome *", email: "E-mail *", organization: "Organização", type: "Tipo de parceiro", country: "País", city: "Cidade", website: "Site", proposal: "Apresentação / proposta", proposalPlaceholder: "Atividade, proposta, documentos ou necessidades de cooperação…", submit: "ENVIAR PEDIDO", error: "Ocorreu um erro. Verifique os campos e tente novamente.", types: ["Universidade", "Escola", "Empresa", "Fornecedor", "Agência", "Investidor", "Promotor imobiliário", "Instituição", "Organização", "Outro"] },
    partnersPage: { eyebrow: "ECOSSISTEMA ICX", title: "Parceiros e organizações.", intro: "Cada ficha indica o tipo de relação. A classificação é controlada pela administração e nunca deduzida de fontes públicas.", ruleTitle: "Regra de apresentação das relações", ruleBody: "Nenhuma organização pode ser apresentada como parceira oficial da ICX POWER SOLUTIONS sem confirmação explícita. O tipo validado pela administração é a referência.", collaboration: "NOVA COLABORAÇÃO", collaborationTitle: "Deseja apresentar a sua organização?", become: "TORNAR-SE PARCEIRO", visit: "VISITAR O SITE", explore: "VER INFORMAÇÕES", commercialPending: "Parceiro comercial — confirmação pendente", lorondo: "O seu site público apresenta serviços de transporte, expedição, recursos humanos e consultoria.", association: "Associação referenciada", aaft: "A AAFT é uma associação criada na Roménia por Jean Lansana KOUNDOUNO e K Marcel TRAORE. Não é uma universidade e não se presume uma parceria ICX." },
    dossierPage: { secure: "ESPAÇO SEGURO", loginTitle: "Inicie sessão para aceder ao seu dossiê ICX.", loginBody: "O dossiê permite guardar o projeto, receber estados e enviar documentos autorizados conforme os seus direitos.", loginButton: "INICIAR SESSÃO", hero: "O MEU DOSSIÊ ICX", title: "O seu projeto num só lugar.", intro: "Gerir pedidos, consultar etapas e enviar documentos apenas no espaço autenticado.", requests: "OS MEUS PEDIDOS", current: "Dossiês em curso", newFile: "NOVO DOSSIÊ", updated: "Atualizado em", emptyTitle: "Ainda não há dossiês.", emptyBody: "Comece por criar um pedido de orientação.", secureDocuments: "DOCUMENTOS SEGUROS", authenticated: "Espaço autenticado", add: "ADICIONAR", uploading: "Carregamento seguro em curso…", newRequest: "NOVO PEDIDO", destination: "Destino *", level: "Nível de estudos *", field: "Área pretendida *", budget: "Orçamento indicativo", language: "Idioma preferido", note: "Nota para a equipa ICX", creating: "A CRIAR…", create: "CRIAR DOSSIÊ", cancel: "CANCELAR", fileError: "Formatos permitidos: PDF, JPG, PNG. Tamanho máximo: 4 MB.", loadError: "Não foi possível carregar os dossiês. Tente novamente.", createError: "Não foi possível criar o dossiê. Verifique os campos.", uploadError: "O carregamento falhou. Tente novamente.", statuses: { DRAFT: "Rascunho", RECEIVED: "Dossiê recebido", VERIFICATION: "Verificação", MISSING_DOCUMENTS: "Documentos em falta", COMPLETE: "Dossiê completo", SUBMISSION: "Envio", PENDING_RESPONSE: "A aguardar resposta", ADMITTED: "Admitido", NOT_ADMITTED: "Não admitido" }, documents: { passport: "Passaporte", national_id: "Documento de identidade", diploma: "Diploma", transcript: "Histórico escolar", cv: "CV", motivation_letter: "Carta de motivação", photo: "Fotografia", language_certificate: "Certificado linguístico", financial_proof: "Comprovativo financeiro", recommendation_letter: "Carta de recomendação", other: "Outro" }, validations: { pending: "Pendente", accepted: "Aceite", rejected: "Recusado" } },
    institutionPage: { unavailable: "Ficha indisponível", unavailableBody: "Esta instituição pode ainda estar em verificação.", back: "VOLTAR AO DIRETÓRIO", directory: "DIRETÓRIO DE UNIVERSIDADES", presentation: "APRESENTAÇÃO", publicInfo: "INFORMAÇÕES PÚBLICAS", country: "País", city: "Cidade", programmes: "Programas / níveis", languages: "Idiomas", visit: "VISITAR O SITE OFICIAL", admission: "VER ADMISSÃO", submit: "ENVIAR O MEU DOSSIÊ PELA ICX" }, universitiesPage: { noResults: "Nenhuma instituição encontrada." },
    workPage: { guidanceTitle: "Apoio documentado, passo a passo.", guidanceBody: "A ICX orienta para fontes oficiais e ajuda na preparação administrativa de projetos profissionais na Roménia ou Polónia.", steps: ["Análise do perfil e projeto profissional", "Orientação para fontes e autoridades oficiais", "Preparação conforme os documentos pedidos", "Acompanhamento sem promessa de resultado"], romania: "Roménia", romaniaNote: "Informações oficiais da Inspeção-Geral de Imigração.", poland: "Polónia", polandNote: "Informações oficiais do Gabinete polaco para Estrangeiros.", mobilityTitle: "Tem um projeto de mobilidade profissional?", mobilityBody: "Apresente a situação, profissão, país de residência e objetivo. Os pedidos são analisados conforme os serviços disponíveis.", mobilityButton: "DESCREVER O MEU PROJETO" },
    disclosure: "A ICX POWER SOLUTIONS apoia candidatos em orientação, admissão e assistência administrativa conforme os serviços disponíveis. Critérios, taxas, prazos, decisões e permissões são da responsabilidade das instituições e autoridades competentes e devem ser confirmados nas fontes oficiais.", institutionMeta: { relation: "Instituição referenciada", summary: "Esta instituição é referenciada para encaminhar candidatos para as suas informações oficiais.", verified: "Fonte oficial consultada — confirme novamente antes de se candidatar.", programmes: "Consulte os programas no site oficial", languages: "Verificar para cada programa" },
  },
  ar: {
    layout: { homeAria: "الصفحة الرئيسية لـ ICX POWER SOLUTIONS", navAria: "التنقل الرئيسي", theme: "تغيير المظهر", language: "اختيار اللغة", openMenu: "فتح القائمة", closeMenu: "إغلاق القائمة", backToTop: "العودة إلى الأعلى", projectStudy: "الدراسة", projectWork: "تصاريح العمل", projectSourcing: "التوريد", projectPartnership: "الشراكة", footerDescription: "منصة دولية للدراسة وتصاريح العمل والعقارات والتجارة والتوريد.", explore: "استكشف", transparency: "الشفافية", legal: "الإشعار القانوني — سيُستكمل", privacy: "سياسة الخصوصية — ستُستكمل", data: "حماية البيانات — ستُستكمل" },
    homePage: { imageAlt: "فريق دولي يتعاون في مشروع عالمي", heroEyebrow: "منصة دولية للأعمال والفرص", heroTitle: "نربط الفرص. نبني مستقبلاً عالمياً.", intro: "منصة دولية للدراسة والتوريد والعقارات وتطوير المشاريع.", studyCta: "الدراسة في الخارج", sourcingCta: "التوريد الدولي", startEyebrow: "ابدأ هنا", lookingFor: "ما الذي تبحث عنه؟", selectIntro: "اختر نقطة البداية. يقود كل مسار إلى معلومات مفيدة، وعند توفر الخدمة، إلى طلب تديره ICX.", explore: "استكشف", studyImageAlt: "طلاب دوليون يراجعون خيارات الدراسة", studyEyebrow: "التوجيه الدولي", studyTitle: "يبدأ مشروعك الدراسي بمصادر موثوقة.", studyBody: "ابحث عن المؤسسات وراجع مواقعها الرسمية ونظّم ملفك. ICX ليست جامعة ولا تدعي أي شراكة غير مؤكدة.", studyButton: "اكتشف المسار", journeyEyebrow: "مسار بسيط وموجّه", journeyTitle: "طريق واضح من النية إلى العمل.", safety: "لا معلومات حساسة بلا مصدر.", timeline: [["01", "الاستكشاف", "البلد والمستوى والمجال والميزانية واللغة."], ["02", "الاختيار", "راجع المصادر الرسمية للمؤسسات."], ["03", "ملف ICX", "أنشئ مساحتك وأرسل العناصر المطلوبة."], ["04", "المتابعة", "تابع الحالات وطلبات المعلومات الإضافية."]], transparencyEyebrow: "الشفافية منذ التصميم", transparencyTitle: "معلومات منفصلة لقرارات واعية.", transparencyBody: "تميّز المنصة بين المؤسسات وقنواتها الرسمية ودعم ICX. ويُعرض نوع العلاقة بصورة قابلة للتحقق.", privacyTitle: "الخصوصية", privacyBody: "وصول مضبوط وتخزين منفصل للمستندات الحساسة.", internationalTitle: "دولي", internationalBody: "واجهة متعددة اللغات مع دعم الكتابة من اليمين إلى اليسار.", teamEyebrow: "فريقنا", teamTitle: "تنسيق بشري وراء كل مسار.", teamBody: "يشرف هؤلاء المسؤولون على حوكمة منصة ICX وتنسيقها.", portrait: "صورة", operationsRole: "مسؤول العمليات والتنسيق", operationsBody: "تنسيق العمليات ومتابعة المسارات وتنظيم التبادلات الدولية.", legalRole: "الممثل القانوني", legalBody: "الحوكمة والرؤية المؤسسية والتطوير المسؤول لمنصة ICX." },
    serviceCards: { study: ["الدراسة في الخارج", "التوجيه الدولي", "التوجيه والقبول والإعداد الإداري بالاستناد إلى المصادر الرسمية."], work: ["تصاريح العمل", "رومانيا وبولندا", "مساعدة إدارية للعمل في رومانيا أو بولندا."], sourcing: ["التوريد الدولي", "DealFlare والتوريد", "نظّم احتياجاتك ومراحل البحث عن الموردين."], realEstate: ["فرص عقارية", "الاستثمار والتنقل", "حضّر بحثاً دولياً دون إعلانات غير متحقق منها."], commerce: ["التجارة الإلكترونية والأعمال", "النمو التجاري", "أساس للكتالوجات وطلبات الأسعار والعمليات المستقبلية."], partnership: ["كن شريكاً", "التعاون", "قدّم منظمتك لمراجعة مسؤولة."], property: ["التكليفات والمشاريع", "إدارة الفرص", "مسار لتأهيل المشاريع والتعارف المهني."] },
    studyPage: { eyebrow: "التوجيه الدولي", title: "مسار دراسي قائم على الوضوح.", intro: "حدّد مشروعك واكتشف المؤسسات وراجع قنواتها الرسمية. تعمل ICX في حدود الخدمات المتاحة.", guided: "مسار موجّه", steps: ["اختيار الوجهة", "تحديد المستوى والمجال", "مراجعة المعلومات الرسمية", "إنشاء ملف ICX", "إعداد المستندات المطلوبة", "متابعة التقدم"], fileTitle: "مساحة ملفك", fileBody: "أنشئ حساباً لحفظ تفضيلاتك وإعداد طلبك ورفع الملفات المسموح بها.", fileButton: "إنشاء ملفي", destinationsEyebrow: "وجهات للاستكشاف", destinationsTitle: "ابدأ بوجهتك.", universityButton: "البحث عن جامعة", destinations: ["رومانيا", "فرنسا", "ألمانيا", "بلجيكا", "إسبانيا", "البرتغال", "إيطاليا", "هولندا", "بولندا", "المجر", "أيرلندا", "السويد", "كندا", "الولايات المتحدة", "الصين"], important: "معلومات مهمة", questions: "أسئلة قبل البدء؟", sourcesTitle: "راجع المصادر الرسمية أولاً.", ubb: "القبول الدولي في UBB", aaft: "معلومات جمعية AAFT" },
    servicesPage: { eyebrow: "DEALFLARE والتوريد", title: "خدمات مصممة لربط الفرص المناسبة.", intro: "يمكن للمنصة أن تتطور إلى مساحات للشركاء وكتالوجات وأسواق دون تفعيل وعود أو عمليات غير معتمدة.", access: "فتح المسار", modularTitle: "منصة مرنة وليست واجهة ثابتة.", features: ["كتالوجات وطلبات أسعار", "متابعة الطلبات والرسائل", "ملفات فرص خاضعة للرقابة", "إدارة وصلاحيات دقيقة"] },
    sourcingPage: { imageAlt: "مختصون يراجعون حلاً لوجستياً دولياً", eyebrow: "DEALFLARE والتوريد", title: "التوريد الدولي.", intro: "هل تبحث عن منتج أو مورد أو حل؟ صِف احتياجك. تنظم ICX المراجعة دون ضمان عرض أو سعر أو مورد قبل التحقق.", steps: ["استلام الطلب", "التحليل", "البحث عن الموردين", "الاختيار وعروض الأسعار", "التفاوض", "التحقق والخدمات اللوجستية"], requestEyebrow: "طلب توريد", requestTitle: "اعرض احتياجك.", successTitle: "تم تسجيل طلبك.", successBody: "يمكن للفريق مراجعته في مساحة المتابعة. لا ينشئ هذا النموذج أي التزام تجاري.", name: "الاسم الكامل *", email: "البريد الإلكتروني المهني *", organization: "المنظمة", product: "المنتج المطلوب *", quantity: "الكمية", budget: "الميزانية التقديرية", origin: "بلد المنشأ المفضل", destination: "بلد الوجهة", detail: "وصف مفصل", detailPlaceholder: "المعايير والشهادات والمواعيد وIncoterm أو أي معلومات مفيدة…", submit: "إرسال الطلب", error: "حدث خطأ. تحقق من الحقول وحاول مرة أخرى." },
    partnershipPage: { eyebrow: "طوّر علاقة", title: "كن شريكاً.", intro: "قدّم منظمتك واقتراحك. تتم مراجعة كل طلب قبل الإعلان عن أي صفة للعلاقة.", transparencyLabel: "مبدأ الشفافية:", transparencyBody: "لا تُعرض أي منظمة كشريك رسمي دون تأكيد صريح واعتماد إداري.", successTitle: "تم تسجيل الطلب.", successBody: "يمكن الآن إسناد اقتراحك إلى مسؤول في مساحة الإدارة.", formEyebrow: "نموذج مهني", name: "الاسم *", email: "البريد الإلكتروني *", organization: "المنظمة", type: "نوع الشريك", country: "البلد", city: "المدينة", website: "الموقع الإلكتروني", proposal: "التعريف / الاقتراح", proposalPlaceholder: "النشاط أو الاقتراح أو المستندات أو احتياجات التعاون…", submit: "إرسال الطلب", error: "حدث خطأ. تحقق من الحقول وحاول مرة أخرى.", types: ["جامعة", "مدرسة", "شركة", "مورد", "وكالة", "مستثمر", "مطوّر عقاري", "مؤسسة", "منظمة", "أخرى"] },
    partnersPage: { eyebrow: "منظومة ICX", title: "الشركاء والمنظمات.", intro: "يوضح كل ملف نوع العلاقة. تتحكم الإدارة في التصنيف ولا يُستنتج أبداً من المصادر العامة.", ruleTitle: "قاعدة عرض العلاقات", ruleBody: "لا يجوز عرض أي منظمة كشريك رسمي لـ ICX POWER SOLUTIONS دون تأكيد صريح. نوع العلاقة المعتمد إدارياً هو المرجع.", collaboration: "تعاون جديد", collaborationTitle: "هل ترغب في تقديم منظمتك؟", become: "كن شريكاً", visit: "زيارة الموقع", explore: "عرض المعلومات", commercialPending: "شريك تجاري — بانتظار التأكيد", lorondo: "يعرض موقعها العام خدمات النقل والشحن والموارد البشرية والاستشارات.", association: "جمعية مدرجة", aaft: "AAFT جمعية أنشأها في رومانيا Jean Lansana KOUNDOUNO وK Marcel TRAORE. وهي ليست جامعة ولا يُفترض وجود شراكة مع ICX." },
    dossierPage: { secure: "مساحة آمنة", loginTitle: "سجّل الدخول للوصول إلى ملف ICX.", loginBody: "يتيح لك الملف حفظ مشروعك واستلام الحالات وإرسال المستندات المسموح بها وفق صلاحياتك.", loginButton: "تسجيل الدخول", hero: "ملفي لدى ICX", title: "مشروعك في مكان واحد.", intro: "أدر طلباتك وراجع المراحل وأرسل المستندات فقط عبر مساحتك الموثقة.", requests: "طلباتي", current: "الملفات الحالية", newFile: "ملف جديد", updated: "آخر تحديث", emptyTitle: "لا يوجد ملف بعد.", emptyBody: "ابدأ بإنشاء طلب توجيه.", secureDocuments: "مستندات آمنة", authenticated: "مساحة موثقة", add: "إضافة", uploading: "جارٍ الرفع الآمن…", newRequest: "طلب جديد", destination: "الوجهة *", level: "المستوى الدراسي *", field: "المجال المطلوب *", budget: "الميزانية التقديرية", language: "اللغة المفضلة", note: "ملاحظة لفريق ICX", creating: "جارٍ الإنشاء…", create: "إنشاء الملف", cancel: "إلغاء", fileError: "الصيغ المسموح بها: PDF وJPG وPNG. الحد الأقصى: 4 MB.", loadError: "تعذر تحميل ملفاتك. حاول مرة أخرى.", createError: "تعذر إنشاء الملف. تحقق من الحقول.", uploadError: "فشل الرفع. حاول مرة أخرى.", statuses: { DRAFT: "مسودة", RECEIVED: "تم استلام الملف", VERIFICATION: "التحقق", MISSING_DOCUMENTS: "مستندات ناقصة", COMPLETE: "ملف مكتمل", SUBMISSION: "الإرسال", PENDING_RESPONSE: "بانتظار الرد", ADMITTED: "مقبول", NOT_ADMITTED: "غير مقبول" }, documents: { passport: "جواز السفر", national_id: "بطاقة الهوية", diploma: "الشهادة", transcript: "كشف الدرجات", cv: "السيرة الذاتية", motivation_letter: "خطاب الدافع", photo: "الصورة", language_certificate: "شهادة اللغة", financial_proof: "الإثبات المالي", recommendation_letter: "خطاب التوصية", other: "أخرى" }, validations: { pending: "قيد الانتظار", accepted: "مقبول", rejected: "مرفوض" } },
    institutionPage: { unavailable: "الملف غير متاح", unavailableBody: "قد تكون هذه المؤسسة قيد التحقق.", back: "العودة إلى الدليل", directory: "دليل الجامعات", presentation: "نبذة", publicInfo: "معلومات عامة", country: "البلد", city: "المدينة", programmes: "البرامج / المستويات", languages: "اللغات", visit: "زيارة الموقع الرسمي", admission: "عرض القبول", submit: "إرسال ملفي عبر ICX" }, universitiesPage: { noResults: "لم يتم العثور على مؤسسة." },
    workPage: { guidanceTitle: "دعم موثّق خطوة بخطوة.", guidanceBody: "توجّه ICX المتقدمين إلى المصادر الرسمية وتساعد في الإعداد الإداري للمشاريع المهنية في رومانيا أو بولندا.", steps: ["تحليل الملف والمشروع المهني", "التوجيه إلى المصادر والسلطات الرسمية", "الإعداد وفق المستندات المطلوبة", "المتابعة دون وعد بالنتيجة"], romania: "رومانيا", romaniaNote: "معلومات رسمية من المفتشية العامة للهجرة.", poland: "بولندا", polandNote: "معلومات رسمية من المكتب البولندي لشؤون الأجانب.", mobilityTitle: "هل لديك مشروع تنقل مهني؟", mobilityBody: "اعرض وضعك ومهنتك وبلد إقامتك وهدفك. تتم دراسة الطلبات وفق الخدمات المتاحة.", mobilityButton: "وصف مشروعي" },
    disclosure: "تدعم ICX POWER SOLUTIONS المتقدمين بالتوجيه والقبول والمساعدة الإدارية وفق الخدمات المتاحة. وتبقى المعايير والرسوم والمواعيد والقرارات والتصاريح من مسؤولية المؤسسات والسلطات المعنية، ويجب تأكيدها من مصادرها الرسمية.", institutionMeta: { relation: "مؤسسة مدرجة", summary: "أُدرجت هذه المؤسسة لتوجيه المتقدمين إلى معلوماتها الرسمية.", verified: "تمت مراجعة المصدر الرسمي — تحقّق منه مجدداً قبل التقديم.", programmes: "راجع البرامج على الموقع الرسمي", languages: "تحقق لكل برنامج" },
  },
} as const;

export const translations = Object.fromEntries(
  (Object.keys(navigationTranslations) as Locale[]).map((locale) => [locale, { ...navigationTranslations[locale], ...pageTranslations[locale] }]),
) as { [L in Locale]: typeof navigationTranslations[L] & typeof pageTranslations[L] };
export type Translation = (typeof translations)[Locale];
export function text(locale: Locale): Translation { return translations[locale]; }

export function localizedServices(locale: Locale): Service[] {
  const cards = pageTranslations[locale].serviceCards;
  const copy = [cards.study, cards.work, cards.sourcing, cards.realEstate, cards.commerce, cards.partnership, cards.property];
  return services.map((service, index) => ({ ...service, title: copy[index][0], eyebrow: copy[index][1], description: copy[index][2] }));
}

export function localizedInstitution(institution: Institution, locale: Locale): Institution {
  const meta = pageTranslations[locale].institutionMeta;
  return { ...institution, country: localizedCountries[locale][institution.country] ?? institution.country, relation: meta.relation, summary: meta.summary, verifiedAt: meta.verified, levels: [meta.programmes], languages: [meta.languages] };
}
export type Service = { key: string; title: string; eyebrow: string; description: string; href: string; icon: LucideIcon; accent: string };
export const services: Service[] = [
  { key: "study", title: "Étudier à l’étranger", eyebrow: "Orientation internationale", description: "Conseils d’orientation, admission et préparation administrative selon les sources officielles.", href: "/study", icon: GraduationCap, accent: "bg-[#000091]" },
  { key: "work-permits", title: "Permis de travail", eyebrow: "Roumanie & Pologne", description: "Orientation administrative pour les personnes qui souhaitent travailler en Roumanie ou en Pologne.", href: "/work-permits", icon: Truck, accent: "bg-[#e1000f]" },
  { key: "sourcing", title: "Sourcing international", eyebrow: "DealFlare & Sourcing", description: "Structurez votre besoin produit ou fournisseur et suivez les étapes de votre recherche.", href: "/sourcing", icon: Truck, accent: "bg-[#6ec5d1]" },
  { key: "real-estate", title: "Opportunités immobilières", eyebrow: "Investissement & mobilité", description: "Préparez une recherche immobilière internationale, sans promesse ni annonce non vérifiée.", href: "/services#real-estate", icon: Building2, accent: "bg-[#a0bf7a]" },
  { key: "commerce", title: "E-commerce & business", eyebrow: "Croissance commerciale", description: "Un socle pour catalogue, demandes de devis et futures opérations B2B ou B2C.", href: "/services#commerce", icon: ShoppingBag, accent: "bg-[#ed8352]" },
  { key: "partnership", title: "Devenir partenaire", eyebrow: "Collaborations", description: "Présentez votre organisation, votre proposition et les éléments utiles à une analyse responsable.", href: "/partnership", icon: Handshake, accent: "bg-[#ab9cdb]" },
  { key: "property", title: "Mandats & projets", eyebrow: "Gestion des opportunités", description: "Un parcours de qualification pour vos projets de mobilité, d’investissement ou de mise en relation.", href: "/services", icon: Warehouse, accent: "bg-[#d6a961]" },
];

type Institution = { slug: string; name: string; country: string; city: string; relation: string; officialSite: string; admissionUrl: string; sourceUrl: string; verifiedAt: string; levels: string[]; languages: string[]; summary: string };
const inst = (slug: string, name: string, country: string, city: string, officialSite: string, admissionUrl: string, summary: string): Institution => ({ slug, name, country, city, relation: "Institution référencée", officialSite, admissionUrl, sourceUrl: admissionUrl, verifiedAt: "Source officielle consultée — à revalider avant toute candidature.", levels: ["Programmes à consulter sur le site officiel"], languages: ["À consulter par programme"], summary });
export const featuredInstitutions: Institution[] = [
  inst("universite-bordeaux", "Université de Bordeaux", "France", "Bordeaux", "https://www.u-bordeaux.com/", "https://www.u-bordeaux.com/Study/international-students", "Université référencée pour l’orientation vers ses informations officielles internationales."),
  inst("universite-grenoble-alpes", "Université Grenoble Alpes", "France", "Grenoble", "https://www.univ-grenoble-alpes.fr/", "https://international.univ-grenoble-alpes.fr/international/home-international-1002177.kjsp", "Université référencée pour l’orientation vers ses informations officielles internationales."),
  inst("universite-paris-cite", "Université Paris Cité", "France", "Paris", "https://u-paris.fr/", "https://u-paris.fr/language/en/admission-as-an-independent-international-student/", "Université référencée pour l’orientation vers ses procédures officielles d’admission internationale."),
  inst("universite-montpellier", "Université de Montpellier", "France", "Montpellier", "https://www.umontpellier.fr/", "https://www.umontpellier.fr/en/international/etudier-a-letranger/venir-etudier-a-luniversite-de-montpellier/", "Université référencée pour l’orientation vers ses procédures officielles."),
  inst("universite-bucarest", "Université de Bucarest", "Roumanie", "Bucarest", "https://unibuc.ro/?lang=en", "https://international.unibuc.ro/home-3/admission-2026-2/", "Université référencée pour l’orientation des candidats UE et hors UE vers les informations officielles."),
  inst("babes-bolyai-university", "Université Babeș-Bolyai", "Roumanie", "Cluj-Napoca", "https://www.ubbcluj.ro/en/", "https://infoadmitere.ubbcluj.ro/en/internationalstudents", "Université référencée pour l’orientation vers les canaux officiels d’information internationale."),
  inst("politehnica-bucarest", "Politehnica Bucarest", "Roumanie", "Bucarest", "https://upb.ro/en/", "https://www.international.upb.ro/admission/applying", "Université référencée pour l’orientation vers sa plateforme officielle de candidature."),
  inst("universite-ouest-timisoara", "Université de l’Ouest de Timișoara", "Roumanie", "Timișoara", "https://www.uvt.ro/en/", "https://admitere.uvt.ro/en/", "Université référencée pour l’orientation vers son portail officiel d’admission."),
  inst("moscow-state-university", "M. V. Lomonosov Moscow State University", "Russie", "Moscou", "https://www.msu.ru/en/", "https://openday.msu.ru/en/admissions", "Université référencée pour l’orientation vers les procédures officielles pour étudiants étrangers."),
  inst("spb-state-university", "St. Petersburg State University", "Russie", "Saint-Pétersbourg", "https://english.spbu.ru/", "https://abiturient.spbu.ru/en/", "Université référencée pour l’orientation vers son bureau officiel d’admission internationale."),
  inst("hse-university", "HSE University", "Russie", "Moscou", "https://www.hse.ru/en/", "https://admissions.hse.ru/en/", "Université référencée pour l’orientation vers son portail officiel de candidature internationale."),
  inst("itmo-university", "ITMO University", "Russie", "Saint-Pétersbourg", "https://en.itmo.ru/en/", "https://en.itmo.ru/en/page/299/admission.htm", "Université référencée pour l’orientation vers ses admissions internationales officielles."),
  inst("peking-university", "Peking University", "Chine", "Beijing", "https://english.pku.edu.cn/", "https://isd.pku.edu.cn/en/", "Université référencée pour l’orientation vers sa division officielle des étudiants internationaux."),
  inst("tsinghua-university", "Tsinghua University", "Chine", "Beijing", "https://www.tsinghua.edu.cn/en/", "https://www.tsinghua.edu.cn/en/Admissions.htm", "Université référencée pour l’orientation vers ses admissions officielles."),
  inst("fudan-university", "Fudan University", "Chine", "Shanghai", "https://www.fudan.edu.cn/en/", "https://iso.fudan.edu.cn/isoenglish/", "Université référencée pour l’orientation vers son bureau officiel des étudiants internationaux."),
  inst("shanghai-jiao-tong", "Shanghai Jiao Tong University", "Chine", "Shanghai", "https://en.sjtu.edu.cn/", "https://en.sjtu.edu.cn/study-sjtu/prospective/application", "Université référencée pour l’orientation vers ses candidatures officielles."),
  inst("university-michigan", "University of Michigan", "États-Unis", "Ann Arbor", "https://www.umich.edu/", "https://admissions.umich.edu/apply/international-applicants", "Université publique référencée pour l’orientation vers ses admissions internationales officielles."),
  inst("uc-berkeley", "University of California, Berkeley", "États-Unis", "Berkeley", "https://www.berkeley.edu/", "https://admissions.berkeley.edu/apply-to-berkeley/international-students/", "Université publique référencée pour l’orientation vers ses admissions internationales officielles."),
  inst("university-washington", "University of Washington", "États-Unis", "Seattle", "https://www.washington.edu/", "https://admit.washington.edu/apply/first-year/how-to-apply/english-proficiency/", "Université publique référencée pour l’orientation vers ses exigences officielles."),
  inst("ut-austin", "The University of Texas at Austin", "États-Unis", "Austin", "https://www.utexas.edu/", "https://admissions.utexas.edu/apply/international-students/", "Université publique référencée pour l’orientation vers son admission internationale officielle."),
  inst("university-toronto", "University of Toronto", "Canada", "Toronto", "https://www.utoronto.ca/", "https://future.utoronto.ca/international-applicants/", "Université référencée pour l’orientation vers ses informations officielles pour candidats internationaux."),
  inst("ubc", "The University of British Columbia", "Canada", "Vancouver", "https://www.ubc.ca/", "https://you.ubc.ca/applying-ubc/requirements/international-high-schools/", "Université référencée pour l’orientation vers ses critères officiels."),
  inst("mcgill", "McGill University", "Canada", "Montréal", "https://www.mcgill.ca/", "https://www.mcgill.ca/internationalstudents/", "Université référencée pour l’orientation vers ses services officiels pour étudiants internationaux."),
  inst("waterloo", "University of Waterloo", "Canada", "Waterloo", "https://uwaterloo.ca/", "https://uwaterloo.ca/future-students/admissions/international-students", "Université référencée pour l’orientation vers ses admissions internationales officielles."),
];
export const applicationTimeline = [["01", "Exploration", "Pays, niveau, domaine, budget et langue."], ["02", "Sélection", "Consultez les sources officielles des établissements."], ["03", "Dossier ICX", "Créez votre espace et déposez les éléments demandés."], ["04", "Suivi", "Suivez les statuts et les demandes de compléments."] ] as const;
export const disclosure = "ICX POWER SOLUTIONS accompagne les candidats dans leur processus d’orientation, d’admission et d’assistance administrative selon les établissements et services disponibles. Les critères, frais, délais, décisions et permis relèvent des autorités et établissements concernés et doivent être confirmés sur leurs sources officielles.";

const localizedCountries: Record<Locale, Record<string, string>> = {
  fr: { "Roumanie": "Roumanie", "France": "France", "Allemagne": "Allemagne", "Belgique": "Belgique", "Espagne": "Espagne", "Portugal": "Portugal", "Italie": "Italie", "Pays-Bas": "Pays-Bas", "Pologne": "Pologne", "Hongrie": "Hongrie", "Irlande": "Irlande", "Suède": "Suède", "Canada": "Canada", "États-Unis": "États-Unis", "Chine": "Chine", "Russie": "Russie" },
  en: { "Roumanie": "Romania", "France": "France", "Allemagne": "Germany", "Belgique": "Belgium", "Espagne": "Spain", "Portugal": "Portugal", "Italie": "Italy", "Pays-Bas": "Netherlands", "Pologne": "Poland", "Hongrie": "Hungary", "Irlande": "Ireland", "Suède": "Sweden", "Canada": "Canada", "États-Unis": "United States", "Chine": "China", "Russie": "Russia" },
  ro: { "Roumanie": "România", "France": "Franța", "Allemagne": "Germania", "Belgique": "Belgia", "Espagne": "Spania", "Portugal": "Portugalia", "Italie": "Italia", "Pays-Bas": "Țările de Jos", "Pologne": "Polonia", "Hongrie": "Ungaria", "Irlande": "Irlanda", "Suède": "Suedia", "Canada": "Canada", "États-Unis": "Statele Unite", "Chine": "China", "Russie": "Rusia" },
  pt: { "Roumanie": "Roménia", "France": "França", "Allemagne": "Alemanha", "Belgique": "Bélgica", "Espagne": "Espanha", "Portugal": "Portugal", "Italie": "Itália", "Pays-Bas": "Países Baixos", "Pologne": "Polónia", "Hongrie": "Hungria", "Irlande": "Irlanda", "Suède": "Suécia", "Canada": "Canadá", "États-Unis": "Estados Unidos", "Chine": "China", "Russie": "Rússia" },
  ar: { "Roumanie": "رومانيا", "France": "فرنسا", "Allemagne": "ألمانيا", "Belgique": "بلجيكا", "Espagne": "إسبانيا", "Portugal": "البرتغال", "Italie": "إيطاليا", "Pays-Bas": "هولندا", "Pologne": "بولندا", "Hongrie": "المجر", "Irlande": "أيرلندا", "Suède": "السويد", "Canada": "كندا", "États-Unis": "الولايات المتحدة", "Chine": "الصين", "Russie": "روسيا" },
};

export const fallbackCopy: Record<Locale, { loading: string; title: string; body: string; home: string }> = {
  fr: { loading: "Chargement…", title: "Page introuvable", body: "La page que vous recherchez n’existe pas ou a été déplacée.", home: "Retour à l’accueil" },
  en: { loading: "Loading…", title: "Page not found", body: "The page you are looking for does not exist or has been moved.", home: "Back to home" },
  ro: { loading: "Se încarcă…", title: "Pagina nu a fost găsită", body: "Pagina pe care o cauți nu există sau a fost mutată.", home: "Înapoi la pagina principală" },
  pt: { loading: "A carregar…", title: "Página não encontrada", body: "A página que procura não existe ou foi movida.", home: "Voltar ao início" },
  ar: { loading: "جارٍ التحميل…", title: "الصفحة غير موجودة", body: "الصفحة التي تبحث عنها غير موجودة أو تم نقلها.", home: "العودة إلى الرئيسية" },
};
