import PublicLayout from "@/components/PublicLayout";
import { useLocale } from "@/contexts/LocaleContext";
import { ArrowRight, CheckCircle2, MessageCircle, Phone } from "lucide-react";
import { Link } from "wouter";

export default function Chat() {
  const { locale } = useLocale();
  const fr = locale === "fr";
  return <PublicLayout><section className="bg-[#07131f] px-5 py-24 text-white lg:px-10"><div className="mx-auto max-w-[1200px]"><div className="flex items-center gap-3 text-[#e5bd69]"><MessageCircle size={24}/><p className="text-[10px] font-bold tracking-[.2em]">{fr ? "ORIENTATION ICX" : "ICX ORIENTATION"}</p></div><h1 className="mt-5 max-w-4xl font-serif text-5xl leading-[.94] tracking-[-.05em] sm:text-7xl">{fr ? "Une première réponse, puis la bonne personne au bon moment." : "A first answer, then the right person at the right time."}</h1><p className="mt-7 max-w-2xl text-base leading-7 text-white/70">{fr ? "Le bouton de discussion à droite vous permet de poser une question sans quitter votre parcours. L’assistant donne une première orientation et transmet les sujets importants à l’équipe ICX." : "Use the discussion button on the right without leaving your journey. The assistant gives initial guidance and points important matters to the ICX team."}</p></div></section><section className="px-5 py-16 lg:px-10"><div className="mx-auto grid max-w-[1100px] gap-6 lg:grid-cols-3"><Feature title={fr ? "Réponse interactive" : "Interactive response"} body={fr ? "Écrivez librement, choisissez une suggestion ou demandez une précision." : "Write freely, choose a suggestion or ask for clarification."}/><Feature title={fr ? "Orientation par secteur" : "Sector guidance"} body={fr ? "Expertise, consulting, mines, start-up, énergie, sourcing et études." : "Expertise, consulting, mining, start-ups, energy, sourcing and study."}/><Feature title={fr ? "Relais humain" : "Human handoff"} body={fr ? "Pour une décision, un contrat ou une validation, l’équipe ICX reprend la main." : "For a decision, contract or validation, the ICX team takes over."}/></div><div className="mx-auto mt-8 flex max-w-[1100px] flex-wrap items-center justify-between gap-5 rounded-3xl bg-[#e6ece8] p-7 dark:bg-[#132b32]"><div><p className="font-semibold">{fr ? "Vous préférez parler directement à l’équipe ?" : "Would you rather speak directly with the team?"}</p><p className="mt-1 text-sm text-[#53616e] dark:text-white/60">icxps.sale@outlook.com · +40 745 437 748</p></div><div className="flex flex-wrap gap-3"><a href="tel:+40745437748" className="inline-flex items-center gap-2 rounded-full bg-[#000091] px-4 py-3 text-xs font-bold text-white"><Phone size={14}/>{fr ? "Appeler" : "Call"}</a><Link href="/partnership" className="inline-flex items-center gap-2 rounded-full border border-[#102337]/15 px-4 py-3 text-xs font-bold dark:border-white/15">{fr ? "Envoyer une demande" : "Send a request"}<ArrowRight size={14}/></Link></div></div></section></PublicLayout>;
}
function Feature({ title, body }: { title: string; body: string }) { return <article className="rounded-3xl border border-[#173149]/10 bg-white p-7 dark:border-white/10 dark:bg-[#102337]"><CheckCircle2 className="text-[#6f9a77]" size={22}/><h2 className="mt-9 text-xl font-semibold">{title}</h2><p className="mt-3 text-sm leading-6 text-[#63717d] dark:text-white/60">{body}</p></article>; }
