import PublicLayout from "@/components/PublicLayout";
import { AIChatBox, type Message } from "@/components/AIChatBox";
import { useLocale } from "@/contexts/LocaleContext";
import { trpc } from "@/lib/trpc";
import { MessageCircle, ShieldCheck } from "lucide-react";
import { useState } from "react";

export default function Chat() {
  const { locale } = useLocale();
  const [messages, setMessages] = useState<Message[]>([]);
  const chat = trpc.ai.chat.useMutation({ onSuccess: (answer) => setMessages((current) => [...current, { role: "assistant", content: answer }]) });
  const send = (content: string) => { const next = [...messages, { role: "user" as const, content }]; setMessages(next); chat.mutate({ locale, messages: next.filter((message) => message.role !== "system").map(({ role, content: text }) => ({ role: role as "user" | "assistant", content: text })) }); };
  const fr = locale === "fr";
  return <PublicLayout><section className="bg-[#07131f] px-5 py-16 text-white lg:px-10"><div className="mx-auto max-w-5xl"><div className="flex items-center gap-3 text-[#e5bd69]"><MessageCircle size={25}/><span className="text-[10px] font-bold tracking-[.18em]">{fr ? "DISCUSSION D’ORIENTATION" : "ORIENTATION CHAT"}</span></div><h1 className="mt-5 max-w-3xl font-serif text-5xl leading-[.95] tracking-[-.05em] sm:text-6xl">{fr ? "Obtenez une première information avant la réponse de l’équipe ICX." : "Get initial information before the ICX team responds."}</h1><p className="mt-6 max-w-2xl text-base leading-7 text-white/65">{fr ? "L’assistant vous aide à comprendre les parcours. Il ne remplace pas une décision humaine et ne garantit ni emploi, permis, admission, prix ou partenariat." : "The assistant helps explain the available paths. It does not replace a human decision and guarantees no job, permit, admission, price or partnership."}</p></div></section><section className="px-5 py-12 lg:px-10"><div className="mx-auto grid max-w-5xl gap-6 lg:grid-cols-[1fr_2fr]"><aside className="rounded-3xl bg-[#e6ece8] p-6 dark:bg-[#132b32]"><ShieldCheck className="text-[#b88429]" size={28}/><h2 className="mt-7 font-semibold">{fr ? "À retenir" : "Please note"}</h2><p className="mt-3 text-sm leading-6 text-[#53616e] dark:text-white/70">{fr ? "Pour déposer un dossier, utilisez les pages Études, Permis de travail ou Demande de partenariat. Pour une validation, contactez directement ICX." : "To submit a file, use the Study, Work permits or Partnership pages. For validation, contact ICX directly."}</p><p className="mt-5 text-xs leading-5 text-[#53616e] dark:text-white/60">icxps.sale@outlook.com<br/>Représentant légal : +40 745 437 748<br/>Opérations et coordination : +40 753 413 765</p></aside><AIChatBox messages={messages} onSendMessage={send} isLoading={chat.isPending} height="620px" placeholder={fr ? "Posez votre question…" : "Ask your question…"} emptyStateMessage={fr ? "Commencez la discussion avec l’assistant ICX" : "Start a conversation with the ICX assistant"} suggestedPrompts={fr ? ["Comment fonctionne l’accompagnement aux études ?", "Quels documents préparer pour un permis de travail ?", "Comment devenir partenaire ?"] : ["How does study assistance work?", "Which documents are useful for a work permit request?", "How can an organisation become a partner?"]}/></div></section></PublicLayout>;
}
