import PublicLayout from "@/components/PublicLayout";
import { useLocale } from "@/contexts/LocaleContext";
import { localizedServices } from "@/lib/content";
import { leaders } from "@/lib/leaders";
import { ArrowRight, CheckCircle2, Compass, Globe2, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

export default function Home() {
  const { locale, t } = useLocale();
  const services = localizedServices(locale);
  const team = leaders.map((leader, index) => ({
    ...leader,
    role: index === 0 ? t.homePage.operationsRole : t.homePage.legalRole,
    description: index === 0 ? t.homePage.operationsBody : t.homePage.legalBody,
  }));

  return <PublicLayout>
    <section className="relative isolate min-h-[690px] overflow-hidden bg-[#07131f] text-white"><img src="/images/hero-global-team.jpg" alt={t.homePage.imageAlt} className="absolute inset-0 -z-20 h-full w-full object-cover object-center"/><div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,rgba(7,19,31,.97)_0%,rgba(7,19,31,.88)_32%,rgba(7,19,31,.40)_58%,rgba(7,19,31,.05)_100%)]"/><div className="mx-auto grid min-h-[690px] max-w-[1360px] content-center px-5 py-24 lg:px-10"><div className="max-w-3xl"><div className="mb-7 flex items-center gap-3 text-[10px] font-bold tracking-[.18em] text-[#e5bd69]"><span className="h-px w-8 bg-[#e5bd69]"/>{locale === "fr" ? "EXPERTISE INTERNATIONALE · CONSULTING · SOURCING · ÉTUDES" : "INTERNATIONAL EXPERTISE · CONSULTING · SOURCING · STUDY"}</div><h1 className="font-serif text-5xl font-medium leading-[.94] tracking-[-.05em] sm:text-6xl lg:text-8xl">{locale === "fr" ? "COMPRENDRE LE MONDE. STRUCTURER LES DÉCISIONS. RELIER LES OPPORTUNITÉS." : "UNDERSTAND THE WORLD. STRUCTURE DECISIONS. CONNECT OPPORTUNITIES."}</h1><p className="mt-7 max-w-2xl text-base leading-7 text-white/72 sm:text-lg">{locale === "fr" ? "Une plateforme d’expertise internationale, de consulting, de sourcing et d’études à l’étranger par le conseil et l’orientation." : "A platform for international expertise, consulting, sourcing and study abroad through guidance and structured advice."}</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/expertise-internationale" className="inline-flex items-center gap-3 rounded-full bg-[#d8a94a] px-5 py-3 text-[11px] font-black tracking-[.1em] text-[#07131f]">{locale === "fr" ? "EXPLORER L’EXPERTISE" : "EXPLORE EXPERTISE"} <ArrowRight size={15}/></Link><Link href="/consulting" className="inline-flex items-center gap-3 rounded-full border border-white/25 px-5 py-3 text-[11px] font-black tracking-[.1em] text-white hover:bg-white/10">{locale === "fr" ? "DÉCOUVRIR LE CONSULTING" : "DISCOVER CONSULTING"} <ArrowRight size={15}/></Link></div></div></div><div className="absolute bottom-7 left-5 right-5 mx-auto flex max-w-[1360px] items-end justify-between text-[10px] font-bold tracking-[.12em] text-white/50 lg:left-10 lg:right-10"><span>ICX POWER SOLUTIONS SRL</span><span>01 — 06</span></div></section>
    <section className="bg-[#f7f6f1] px-5 py-16 text-[#102337] dark:bg-[#0c1c2a] dark:text-white lg:px-10"><div className="mx-auto max-w-[1360px]"><div className="grid gap-4 md:grid-cols-3"><Link href="/expertise-internationale" className="group overflow-hidden rounded-3xl bg-[#102337] text-white"><img src="/images/sourcing-logistics.jpg" alt="International expertise" className="h-52 w-full object-cover opacity-75 transition group-hover:scale-105"/><div className="p-6"><p className="text-[10px] font-bold tracking-[.16em] text-[#e5bd69]">01</p><h2 className="mt-3 font-serif text-3xl">{locale === "fr" ? "Expertise internationale" : "International expertise"}</h2><p className="mt-3 text-sm leading-6 text-white/65">{locale === "fr" ? "Marchés, implantation, ressources, énergie et alliances." : "Markets, expansion, resources, energy and alliances."}</p></div></Link><Link href="/consulting" className="group overflow-hidden rounded-3xl bg-[#e6ece8] text-[#102337] dark:bg-[#132b32] dark:text-white"><img src="/images/home/consulting-advisory.jpg" alt={locale === "fr" ? "Réunion de conseil stratégique entre professionnels" : "Professional strategic consulting meeting"} className="h-52 w-full object-cover object-[50%_60%] opacity-80 transition group-hover:scale-105"/><div className="p-6"><p className="text-[10px] font-bold tracking-[.16em] text-[#b88429]">02</p><h2 className="mt-3 font-serif text-3xl">Consulting</h2><p className="mt-3 text-sm leading-6 text-[#53616e] dark:text-white/65">{locale === "fr" ? "Une méthode humaine pour clarifier une décision." : "A human method for clearer decisions."}</p></div></Link><Link href="/partnerships-strategiques" className="group overflow-hidden rounded-3xl bg-[#d8a94a] text-[#07131f]"><img src="/images/home/strategic-partnerships.jpg" alt={locale === "fr" ? "Signature d’un accord de partenariat international" : "International strategic partnership agreement"} className="h-52 w-full object-cover object-[50%_62%] opacity-75 mix-blend-multiply transition group-hover:scale-105"/><div className="p-6"><p className="text-[10px] font-bold tracking-[.16em]">03</p><h2 className="mt-3 font-serif text-3xl">{locale === "fr" ? "Partenariats stratégiques" : "Strategic partnerships"}</h2><p className="mt-3 text-sm leading-6">{locale === "fr" ? "Mines, start-up, énergie, financement et coopération." : "Mining, start-ups, energy, financing and cooperation."}</p></div></Link></div></div></section>
    <section className="bg-[#f7f6f1] px-5 py-20 text-[#102337] dark:bg-[#0c1c2a] dark:text-white lg:px-10"><div className="mx-auto max-w-[1360px]"><div className="grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-[10px] font-bold tracking-[.18em] text-[#b88429]">{t.homePage.startEyebrow}</p><h2 className="mt-4 max-w-sm font-serif text-4xl leading-none tracking-[-.04em] sm:text-5xl">{t.homePage.lookingFor}</h2></div><p className="max-w-xl self-end text-base leading-7 text-[#53616e] dark:text-white/65">{t.homePage.selectIntro}</p></div><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{services.map((service, index) => <Link key={service.key} href={service.href} className="group relative overflow-hidden rounded-2xl border border-[#173149]/10 bg-white p-6 shadow-[0_18px_45px_rgba(7,19,31,.05)] transition-all hover:-translate-y-1 hover:shadow-[0_24px_65px_rgba(7,19,31,.12)] dark:bg-[#102337] dark:border-white/10"><div className={`absolute right-0 top-0 h-1 w-16 ${service.accent}`}/><div className="flex items-start justify-between"><span className="text-[11px] font-bold text-[#96a0a6]">0{index + 1}</span><service.icon size={22} className="text-[#b88429]"/></div><p className="mt-8 text-[10px] font-bold tracking-[.14em] text-[#b88429]">{service.eyebrow}</p><h3 className="mt-2 text-xl font-semibold tracking-tight">{service.title}</h3><p className="mt-3 text-sm leading-6 text-[#63717d] dark:text-white/60">{service.description}</p><span className="mt-5 inline-flex items-center gap-2 text-[10px] font-black tracking-[.1em]">{t.homePage.explore} <ArrowRight className="transition-transform group-hover:translate-x-1" size={14}/></span></Link>)}</div></div></section>
    <section className="grid overflow-hidden bg-[#e6ece8] lg:grid-cols-2 dark:bg-[#132b32]"><div className="min-h-[410px] overflow-hidden"><img src="/images/study-guidance.jpg" alt={t.homePage.studyImageAlt} className="h-full w-full object-cover"/></div><div className="flex flex-col justify-center px-5 py-16 lg:px-16"><p className="text-[10px] font-bold tracking-[.18em] text-[#b88429]">{t.homePage.studyEyebrow}</p><h2 className="mt-4 max-w-xl font-serif text-4xl leading-[.98] tracking-[-.045em] sm:text-5xl">{t.homePage.studyTitle}</h2><p className="mt-5 max-w-xl text-base leading-7 text-[#53616e] dark:text-white/65">{t.homePage.studyBody}</p><div className="mt-8"><Link href="/study" className="inline-flex items-center gap-3 rounded-full bg-[#102337] px-5 py-3 text-[11px] font-bold tracking-[.1em] text-white dark:bg-[#d8a94a] dark:text-[#07131f]">{t.homePage.studyButton} <ArrowRight size={15}/></Link></div></div></section>
    <section className="bg-[#07131f] px-5 py-20 text-white lg:px-10"><div className="mx-auto max-w-[1360px]"><div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><p className="text-[10px] font-bold tracking-[.18em] text-[#e5bd69]">{t.homePage.journeyEyebrow}</p><h2 className="mt-4 max-w-2xl font-serif text-4xl leading-none tracking-[-.04em] sm:text-5xl">{t.homePage.journeyTitle}</h2></div><div className="flex items-center gap-5 text-sm text-white/55"><CheckCircle2 className="text-[#e5bd69]" size={19}/> {t.homePage.safety}</div></div><div className="mt-12 grid gap-px overflow-hidden rounded-2xl bg-white/15 md:grid-cols-4">{t.homePage.timeline.map(([number, title, body]) => <div key={number} className="min-h-52 bg-[#0b1b2a] p-6"><p className="font-serif text-4xl text-[#e5bd69]">{number}</p><h3 className="mt-10 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-white/60">{body}</p></div>)}</div></div></section>
    <section className="bg-[#f7f6f1] px-5 py-20 text-[#102337] dark:bg-[#0c1c2a] dark:text-white lg:px-10"><div className="mx-auto grid max-w-[1360px] gap-8 lg:grid-cols-[1fr_.85fr]"><div className="rounded-3xl bg-[#102337] p-8 text-white sm:p-12"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-[#d8a94a] text-[#07131f]"><Compass size={22}/></div><p className="mt-10 text-[10px] font-bold tracking-[.18em] text-[#e5bd69]">{t.homePage.transparencyEyebrow}</p><h2 className="mt-4 max-w-xl font-serif text-4xl leading-none tracking-[-.04em]">{t.homePage.transparencyTitle}</h2><p className="mt-5 max-w-lg text-sm leading-7 text-white/65">{t.homePage.transparencyBody}</p></div><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-3xl border border-[#173149]/10 p-7 dark:border-white/10"><ShieldCheck className="text-[#b88429]" size={24}/><h3 className="mt-12 text-xl font-semibold">{t.homePage.privacyTitle}</h3><p className="mt-3 text-sm leading-6 text-[#63717d] dark:text-white/60">{t.homePage.privacyBody}</p></div><div className="rounded-3xl border border-[#173149]/10 p-7 dark:border-white/10"><Globe2 className="text-[#b88429]" size={24}/><h3 className="mt-12 text-xl font-semibold">{t.homePage.internationalTitle}</h3><p className="mt-3 text-sm leading-6 text-[#63717d] dark:text-white/60">{t.homePage.internationalBody}</p></div></div></div></section>
    <section className="bg-[#e6ece8] px-5 py-20 text-[#102337] dark:bg-[#132b32] dark:text-white lg:px-10"><div className="mx-auto max-w-[1360px]"><div className="max-w-2xl"><p className="text-[10px] font-bold tracking-[.18em] text-[#b88429]">{t.homePage.teamEyebrow}</p><h2 className="mt-4 font-serif text-4xl leading-none tracking-[-.04em] sm:text-5xl">{t.homePage.teamTitle}</h2><p className="mt-5 text-base leading-7 text-[#53616e] dark:text-white/65">{t.homePage.teamBody}</p></div><div className="mt-10 grid gap-5 md:grid-cols-2">{team.map((leader) => <article key={leader.name} className="flex gap-5 rounded-3xl bg-white p-6 shadow-sm dark:bg-[#102337]"><div className="grid h-20 w-20 shrink-0 place-items-center overflow-hidden rounded-full bg-[#d8a94a] font-serif text-xl text-[#07131f]">{leader.image ? <img src={leader.image} alt={`${t.homePage.portrait} ${leader.name}`} className="h-full w-full object-cover object-top" /> : leader.initials}</div><div><h3 className="text-xl font-semibold tracking-tight">{leader.name}</h3><p className="mt-1 text-[10px] font-bold tracking-[.12em] text-[#b88429]">{leader.role}</p><p className="mt-4 text-sm leading-6 text-[#63717d] dark:text-white/60">{leader.description}</p></div></article>)}</div></div></section>
    <section className="border-t border-[#173149]/10 bg-white px-5 py-12 dark:border-white/10 dark:bg-[#102337] lg:px-10"><div className="mx-auto max-w-[1360px]"><p className="text-[10px] font-bold tracking-[.16em] text-[#b88429]">{locale === "fr" ? "RÉFÉRENCES D’ENREGISTREMENT" : "REGISTRATION DETAILS"}</p><h2 className="mt-4 text-2xl font-semibold">ICX POWER SOLUTIONS SRL</h2><dl className="mt-5 grid gap-3 text-sm leading-6 text-[#5c6b75] dark:text-white/65 sm:grid-cols-2 lg:grid-cols-4"><div><dt className="font-semibold text-[#102337] dark:text-white">CUI / CIF</dt><dd>54675848</dd></div><div><dt className="font-semibold text-[#102337] dark:text-white">{locale === "fr" ? "Registre du Commerce" : "Trade Register"}</dt><dd>J2026031336000</dd></div><div><dt className="font-semibold text-[#102337] dark:text-white">EUID</dt><dd>ROONRC.J2026031336000</dd></div><div><dt className="font-semibold text-[#102337] dark:text-white">{locale === "fr" ? "Siège social" : "Registered office"}</dt><dd>Str. Hlincea nr. 47, Iași, Romania</dd></div></dl><p className="mt-5 max-w-3xl text-xs leading-5 text-[#78858e]">{locale === "fr" ? "Société enregistrée le 13 mai 2026. Activité principale : CAEN 7020 — activités de conseil en affaires et management. Les informations doivent être revalidées sur les registres officiels avant tout usage juridique." : "Company registered on 13 May 2026. Main activity: CAEN 7020 — business and management consultancy. Revalidate the information against official registers before any legal use."}</p><a href="https://www.onrc.ro/" target="_blank" rel="noreferrer" className="mt-4 inline-flex text-xs font-bold text-[#000091] dark:text-[#e5bd69]">{locale === "fr" ? "Consulter le registre officiel ONRC" : "Consult the official ONRC register"}</a></div></section>
  </PublicLayout>;
}
