import PublicLayout from "@/components/PublicLayout";
import { useLocale } from "@/contexts/LocaleContext";
import { featuredInstitutions, localizedInstitution } from "@/lib/content";
import { ArrowLeft, ExternalLink, FileText, ShieldCheck } from "lucide-react";
import { Link, useRoute } from "wouter";

export default function InstitutionDetail() {
  const { locale, t } = useLocale();
  const [, params] = useRoute("/universities/:slug");
  const source = featuredInstitutions.find((item) => item.slug === params?.slug);
  const institution = source ? localizedInstitution(source, locale) : undefined;
  if (!institution) return <PublicLayout><section className="grid min-h-[55vh] place-items-center px-5 text-center"><div><h1 className="font-serif text-4xl">{t.institutionPage.unavailable}</h1><p className="mt-3 text-sm text-[#677681]">{t.institutionPage.unavailableBody}</p><Link href="/universities" className="mt-6 inline-flex items-center gap-2 text-[10px] font-black tracking-[.1em]"><ArrowLeft size={14}/> {t.institutionPage.back}</Link></div></section></PublicLayout>;
  const infoLabel = locale === "fr" ? "Info sur l’Université" : "University information";
  const contactLabel = locale === "fr" ? "Contacter ICX POWER SOLUTIONS SRL" : "Contact ICX POWER SOLUTIONS SRL";
  return <PublicLayout><section className="bg-[#07131f] px-5 py-16 text-white lg:px-10"><div className="mx-auto max-w-[1100px]"><Link href="/universities" className="inline-flex items-center gap-2 text-[10px] font-bold tracking-[.1em] text-[#e5bd69]"><ArrowLeft size={14}/> {t.institutionPage.directory}</Link><p className="mt-10 text-[10px] font-bold tracking-[.16em] text-[#e5bd69]">{institution.relation}</p><h1 className="mt-4 font-serif text-5xl tracking-[-.05em] sm:text-6xl">{institution.name}</h1><p className="mt-5 text-sm text-white/65">{institution.country} · {institution.city}</p></div></section><section className="px-5 py-14 lg:px-10"><div className="mx-auto grid max-w-[1100px] gap-8 lg:grid-cols-[1.2fr_.8fr]"><article><p className="text-[10px] font-bold tracking-[.16em] text-[#b88429]">{infoLabel}</p><p className="mt-4 text-base leading-8 text-[#54636f] dark:text-white/70">{institution.summary}</p><div className="mt-8 rounded-2xl bg-[#e6ece8] p-5 dark:bg-[#132b32]"><div className="flex gap-3"><ShieldCheck className="mt-0.5 shrink-0 text-[#6f9a77]" size={18}/><p className="text-sm leading-6">{institution.verifiedAt}</p></div></div><p className="mt-8 text-sm leading-7 text-[#5d6b76] dark:text-white/65">{t.disclosure}</p></article><aside className="rounded-3xl border border-[#173149]/10 bg-white p-6 dark:border-white/10 dark:bg-[#102337]"><p className="text-[10px] font-bold tracking-[.16em] text-[#b88429]">{t.institutionPage.publicInfo}</p><dl className="mt-6 grid gap-5 text-sm"><div><dt className="text-[#667681] dark:text-white/55">{t.institutionPage.country}</dt><dd className="mt-1 font-semibold">{institution.country}</dd></div><div><dt className="text-[#667681] dark:text-white/55">{t.institutionPage.city}</dt><dd className="mt-1 font-semibold">{institution.city}</dd></div><div><dt className="text-[#667681] dark:text-white/55">{t.institutionPage.programmes}</dt><dd className="mt-1 font-semibold">{institution.levels.join(", ")}</dd></div><div><dt className="text-[#667681] dark:text-white/55">{t.institutionPage.languages}</dt><dd className="mt-1 font-semibold">{institution.languages.join(", ")}</dd></div></dl><div className="mt-8 grid gap-3"><a href={institution.officialSite} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-full bg-[#102337] px-4 py-3 text-[10px] font-black tracking-[.08em] text-white dark:bg-[#d8a94a] dark:text-[#07131f]">{infoLabel} <ExternalLink size={14}/></a><Link href="/study/contact" className="inline-flex items-center justify-center gap-2 rounded-full border border-[#173149]/15 px-4 py-3 text-[10px] font-black tracking-[.08em] dark:border-white/15">{contactLabel} <FileText size={14}/></Link></div></aside></div></section></PublicLayout>;
}
