import PublicLayout from "@/components/PublicLayout";
import { useLocale } from "@/contexts/LocaleContext";
import { ArrowUpRight, ExternalLink, ShieldAlert } from "lucide-react";
import { Link } from "wouter";

export default function Partners() {
  const { t } = useLocale();
  const copy = t.partnersPage;
  const partners = [
    { name: "LORONDO SERVICES SRL", relation: copy.commercialPending, activity: copy.lorondo, site: "https://lorondo-services.com/", cta: copy.visit },
    { name: "AAFT Association", relation: copy.association, activity: copy.aaft, site: "https://aaft.com/", cta: copy.explore },
  ];
  return <PublicLayout><section className="bg-[#07131f] px-5 py-20 text-white lg:px-10"><div className="mx-auto max-w-[1360px]"><p className="text-[10px] font-bold tracking-[.18em] text-[#e5bd69]">{copy.eyebrow}</p><h1 className="mt-4 font-serif text-5xl tracking-[-.05em] sm:text-6xl">{copy.title}</h1><p className="mt-6 max-w-2xl text-sm leading-7 text-white/65">{copy.intro}</p></div></section><section className="px-5 py-16 lg:px-10"><div className="mx-auto grid max-w-[1360px] gap-5 lg:grid-cols-2">{partners.map((partner, index) => <article key={partner.name} className="rounded-3xl border border-[#173149]/10 bg-white p-8 dark:border-white/10 dark:bg-[#102337]"><span className="text-[10px] font-bold tracking-[.1em] text-[#b88429]">0{index + 1}</span><h2 className="mt-9 text-2xl font-semibold">{partner.name}</h2><div className="mt-4 inline-flex rounded-full bg-[#fff5dd] px-3 py-1 text-[10px] font-bold text-[#8d661f] dark:bg-[#302817] dark:text-[#e5bd69]">{partner.relation}</div><p className="mt-6 text-sm leading-7 text-[#5f6e79] dark:text-white/65">{partner.activity}</p><a href={partner.site} target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center gap-2 rounded-full bg-[#102337] px-4 py-2.5 text-[10px] font-black tracking-[.1em] text-white dark:bg-[#d8a94a] dark:text-[#07131f]">{partner.cta} <ExternalLink size={14}/></a></article>)}</div></section><section className="bg-[#fff5dd] px-5 py-12 dark:bg-[#302817] lg:px-10"><div className="mx-auto flex max-w-[1360px] gap-4"><ShieldAlert className="mt-1 shrink-0 text-[#b88429]"/><div><h2 className="font-semibold">{copy.ruleTitle}</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-[#655f4f] dark:text-white/70">{copy.ruleBody}</p></div></div></section><section className="px-5 py-16 text-center lg:px-10"><p className="text-[10px] font-bold tracking-[.16em] text-[#b88429]">{copy.collaboration}</p><h2 className="mt-4 font-serif text-4xl tracking-[-.04em]">{copy.collaborationTitle}</h2><Link href="/partnership" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#d8a94a] px-5 py-3 text-[10px] font-black tracking-[.1em] text-[#07131f]">{copy.become} <ArrowUpRight size={15}/></Link></section></PublicLayout>;
}
