import PublicLayout from "@/components/PublicLayout";
import { useLocale } from "@/contexts/LocaleContext";
import { localizedServices } from "@/lib/content";
import { ArrowRight, CheckCircle2, Layers3, Quote } from "lucide-react";
import { Link } from "wouter";
export default function Services() {
  const { locale, t } = useLocale(); const copy = t.servicesPage; const services = localizedServices(locale);
  const message = locale === "fr" ? { label: "MESSAGE DU RESPONSABLE DES OPÉRATIONS", title: "Une coordination attentive, de l’orientation au suivi.", body: "Notre rôle est de clarifier chaque demande, de vérifier les informations disponibles et d’organiser les échanges avec les personnes, entreprises et institutions concernées. Nous avançons avec méthode, sans promesse irréaliste, afin que chaque projet dispose d’un prochain pas compréhensible." } : { label: "MESSAGE FROM THE OPERATIONS MANAGER", title: "Careful coordination from guidance to follow-up.", body: "Our role is to clarify each request, verify available information and organise exchanges with the relevant people, companies and institutions. We work methodically and avoid unrealistic promises so that every project has a clear next step." };
  return <PublicLayout><section className="bg-[#07131f] px-5 py-20 text-white lg:px-10"><div className="mx-auto max-w-[1360px]"><p className="text-[10px] font-bold tracking-[.18em] text-[#e5bd69]">{copy.eyebrow}</p><h1 className="mt-4 max-w-4xl font-serif text-5xl leading-[.94] tracking-[-.05em] sm:text-7xl">{copy.title}</h1><p className="mt-6 max-w-2xl text-base leading-7 text-white/65">{copy.intro}</p></div></section><section className="px-5 py-16 lg:px-10"><div className="mx-auto grid max-w-[1360px] gap-5 md:grid-cols-2 lg:grid-cols-3">{services.map((service) => <article id={service.key} key={service.key} className="relative overflow-hidden rounded-3xl border border-[#173149]/10 bg-white p-7 dark:border-white/10 dark:bg-[#102337]"><div className={`absolute right-0 top-0 h-1 w-24 ${service.accent}`}/><service.icon className="text-[#b88429]" size={25}/><p className="mt-10 text-[10px] font-bold tracking-[.14em] text-[#b88429]">{service.eyebrow}</p><h2 className="mt-2 text-2xl font-semibold">{service.title}</h2><p className="mt-4 text-sm leading-7 text-[#61707b] dark:text-white/65">{service.description}</p><Link href={service.href} className="mt-7 inline-flex items-center gap-2 text-[10px] font-black tracking-[.1em]">{copy.access} <ArrowRight size={14}/></Link></article>)}</div></section><section className="bg-[#e6ece8] px-5 py-16 dark:bg-[#132b32] lg:px-10"><div className="mx-auto grid max-w-[1360px] gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><Layers3 className="text-[#b88429]" size={28}/><h2 className="mt-9 font-serif text-4xl leading-none tracking-[-.04em]">{copy.modularTitle}</h2></div><div className="grid gap-5 sm:grid-cols-2">{copy.features.map((item) => <div key={item} className="flex gap-3 text-sm leading-6"><CheckCircle2 className="mt-0.5 shrink-0 text-[#6f9a77]" size={17}/>{item}</div>)}</div></div></section><section className="bg-[#102337] px-5 py-16 text-white lg:px-10"><div className="mx-auto grid max-w-[1100px] gap-8 md:grid-cols-[auto_1fr]"><Quote className="text-[#e5bd69]" size={34}/><div><p className="text-[10px] font-bold tracking-[.16em] text-[#e5bd69]">{message.label}</p><h2 className="mt-4 font-serif text-4xl leading-none">{message.title}</h2><p className="mt-5 max-w-3xl text-base leading-8 text-white/70">{message.body}</p><p className="mt-6 text-[10px] font-bold tracking-[.14em] text-[#e5bd69]">K MARCEL TRAORE — RESPONSABLE DES OPÉRATIONS ET DE LA COORDINATION</p></div></div></section></PublicLayout>;
}
