import PublicLayout from "@/components/PublicLayout";
import { useLocale } from "@/contexts/LocaleContext";
import { ArrowRight, BriefcaseBusiness, CheckCircle2, ShieldAlert } from "lucide-react";
import { Link } from "wouter";

const countries = [
  { name: "Roumanie", official: "https://igi.mai.gov.ro/en/", note: "Informations officielles de l’Inspectorat général pour l’immigration." },
  { name: "Pologne", official: "https://www.gov.pl/web/udsc-en", note: "Informations officielles de l’Office des étrangers polonais." },
];

export default function WorkPermits() {
  const { t } = useLocale();
  return <PublicLayout><section className="bg-[#000091] px-5 py-20 text-white lg:px-10"><div className="mx-auto max-w-[1200px]"><p className="text-[10px] font-bold tracking-[.18em] text-[#ffb000]">ICX POWER SOLUTIONS</p><h1 className="mt-5 max-w-4xl text-5xl font-bold leading-[.98] tracking-[-.04em] sm:text-7xl">{t.workTitle}</h1><p className="mt-7 max-w-2xl text-base leading-7 text-white/80">{t.workIntro}</p></div></section><section className="px-5 py-16 lg:px-10"><div className="mx-auto grid max-w-[1200px] gap-8 lg:grid-cols-[1.1fr_.9fr]"><div><p className="text-[10px] font-bold tracking-[.16em] text-[#000091] dark:text-[#ffb000]">{t.support}</p><h2 className="mt-4 text-3xl font-bold tracking-tight">Un accompagnement documenté, étape par étape.</h2><p className="mt-5 max-w-2xl text-base leading-8 text-[#55555f] dark:text-white/70">{t.supportText}</p><div className="mt-8 grid gap-3">{["Analyse du profil et du projet professionnel", "Orientation vers les sources et autorités officielles", "Préparation administrative selon les documents demandés", "Suivi des compléments sans promesse de résultat"].map((item) => <div key={item} className="flex gap-3 text-sm leading-6"><CheckCircle2 className="mt-0.5 shrink-0 text-[#000091] dark:text-[#ffb000]" size={18}/>{item}</div>)}</div></div><aside className="rounded-2xl border border-[#dddddf] bg-white p-7 shadow-sm dark:border-white/10 dark:bg-[#102337]"><BriefcaseBusiness className="text-[#000091] dark:text-[#ffb000]" size={30}/><h2 className="mt-7 text-2xl font-bold">{t.countries}</h2><div className="mt-6 grid gap-4">{countries.map((country) => <div key={country.name} className="rounded-xl bg-[#f6f6f6] p-4 dark:bg-[#173149]"><h3 className="font-bold">{country.name}</h3><p className="mt-2 text-sm leading-6 text-[#55555f] dark:text-white/70">{country.note}</p><a href={country.official} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-2 text-xs font-bold text-[#000091] dark:text-[#ffb000]">Source officielle <ArrowRight size={14}/></a></div>)}</div></aside></div></section><section className="bg-[#fff5dd] px-5 py-12 dark:bg-[#302817] lg:px-10"><div className="mx-auto flex max-w-[1200px] gap-4"><ShieldAlert className="mt-1 shrink-0 text-[#b34d00]"/><p className="max-w-4xl text-sm leading-7 text-[#3b3b3b] dark:text-white/75">{t.workCaution}</p></div></section><section className="px-5 py-16 lg:px-10"><div className="mx-auto max-w-[1200px] rounded-2xl bg-[#1e1e23] p-8 text-white sm:p-12"><h2 className="text-3xl font-bold">Vous avez un projet de mobilité professionnelle ?</h2><p className="mt-4 max-w-2xl text-white/70">Présentez votre situation, votre métier, votre pays de résidence et votre objectif. Les demandes sont étudiées selon les services disponibles.</p><Link href="/partnership" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#ffb000] px-5 py-3 text-xs font-bold text-[#1e1e23]">DÉCRIRE MON PROJET <ArrowRight size={15}/></Link></div></section></PublicLayout>;
}
