from pathlib import Path
p=Path('/home/ubuntu/work2/client/src/pages/Home.tsx')
s=p.read_text()
needle='</section>\n  </PublicLayout>;'
section='''</section>
    <section className="border-t border-[#173149]/10 bg-white px-5 py-12 dark:border-white/10 dark:bg-[#102337] lg:px-10"><div className="mx-auto max-w-[1360px]"><p className="text-[10px] font-bold tracking-[.16em] text-[#b88429]">{locale === "fr" ? "RÉFÉRENCES D’ENREGISTREMENT" : "REGISTRATION DETAILS"}</p><h2 className="mt-4 text-2xl font-semibold">ICX POWER SOLUTIONS SRL</h2><dl className="mt-5 grid gap-3 text-sm leading-6 text-[#5c6b75] dark:text-white/65 sm:grid-cols-2 lg:grid-cols-4"><div><dt className="font-semibold text-[#102337] dark:text-white">CUI / CIF</dt><dd>54675848</dd></div><div><dt className="font-semibold text-[#102337] dark:text-white">{locale === "fr" ? "Registre du Commerce" : "Trade Register"}</dt><dd>J2026031336000</dd></div><div><dt className="font-semibold text-[#102337] dark:text-white">EUID</dt><dd>ROONRC.J2026031336000</dd></div><div><dt className="font-semibold text-[#102337] dark:text-white">{locale === "fr" ? "Siège social" : "Registered office"}</dt><dd>Str. Hlincea nr. 47, Iași, Romania</dd></div></dl><p className="mt-5 max-w-3xl text-xs leading-5 text-[#78858e]">{locale === "fr" ? "Société enregistrée le 13 mai 2026. Activité principale : CAEN 7020 — activités de conseil en affaires et management. Les informations doivent être revalidées sur les registres officiels avant tout usage juridique." : "Company registered on 13 May 2026. Main activity: CAEN 7020 — business and management consultancy. Revalidate the information against official registers before any legal use."}</p><a href="https://www.onrc.ro/" target="_blank" rel="noreferrer" className="mt-4 inline-flex text-xs font-bold text-[#000091] dark:text-[#e5bd69]">{locale === "fr" ? "Consulter le registre officiel ONRC" : "Consult the official ONRC register"}</a></div></section>
  </PublicLayout>;'''
if needle not in s: raise SystemExit('needle not found')
p.write_text(s.replace(needle, section, 1))
